//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet {
            get {
                object obj = ResourceManager.GetObject("bullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated by CSGO Demos Manager
        ///demoactions
        ///{{
        ///	{0}
        ///}}.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap model {
            get {
                object obj = ResourceManager.GetObject("model", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;
        ///	{{
        ///		factory &quot;ScreenFadeStart&quot;
        ///		name &quot;ScreenFadeStart{0}&quot;
        ///		starttick &quot;{1}&quot;
        ///		duration &quot;1.000&quot;
        ///		holdtime &quot;1.000&quot;
        ///		FFADE_IN &quot;1&quot;
        ///		FFADE_OUT &quot;1&quot;
        ///		r &quot;0&quot;
        ///		g &quot;0&quot;
        ///		b &quot;0&quot;
        ///		a &quot;255&quot;
        ///	}}.
        /// </summary>
        internal static string screen_fade_start {
            get {
                return ResourceManager.GetString("screen_fade_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;
        ///	{{
        ///		factory &quot;SkipAhead&quot;
        ///		name &quot;SkipAhead{0}&quot;
        ///		starttick &quot;{1}&quot;
        ///		skiptotick &quot;{2}&quot;
        ///	}}.
        /// </summary>
        internal static string skip_ahead {
            get {
                return ResourceManager.GetString("skip_ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;
        ///	{{
        ///		factory &quot;PlayCommands&quot;
        ///		name &quot;spec&quot;
        ///		starttick &quot;{1}&quot;
        ///		commands &quot;spec_player_by_accountid {2}&quot;
        ///	}}.
        /// </summary>
        internal static string spec_player {
            get {
                return ResourceManager.GetString("spec_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;
        ///	{{
        ///		factory &quot;StopPlayback&quot;
        ///		name &quot;stop&quot;
        ///		starttick &quot;{1}&quot;
        ///	}}.
        /// </summary>
        internal static string stop_playback {
            get {
                return ResourceManager.GetString("stop_playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;
        ///	{{
        ///		factory &quot;TextMessageStart&quot;
        ///		name &quot;TextMessageStart{0}&quot;
        ///		starttick &quot;{1}&quot;
        ///		message &quot;{2}&quot;
        ///		font &quot;Trebuchet24&quot;
        ///		fadein &quot;0.500&quot;
        ///		fadeout &quot;0.500&quot;
        ///		holdtime &quot;5.000&quot;
        ///		fxtime &quot;0.000&quot;
        ///		FADEINOUT &quot;1&quot;
        ///		x &quot;10.000000&quot;
        ///		y &quot;10.000000&quot;
        ///		r1 &quot;255&quot;
        ///		g1 &quot;255&quot;
        ///		b1 &quot;255&quot;
        ///		a1 &quot;0&quot;
        ///		r2 &quot;0&quot;
        ///		g2 &quot;0&quot;
        ///		b2 &quot;0&quot;
        ///		a2 &quot;0&quot;
        ///	}}.
        /// </summary>
        internal static string text_message_start {
            get {
                return ResourceManager.GetString("text_message_start", resourceCulture);
            }
        }
    }
}
