//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCheckUpdate {
            get {
                return ((bool)(this["EnableCheckUpdate"]));
            }
            set {
                this["EnableCheckUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFolder {
            get {
                return ((string)(this["LastFolder"]));
            }
            set {
                this["LastFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAllFolders {
            get {
                return ((bool)(this["ShowAllFolders"]));
            }
            set {
                this["ShowAllFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int ResolutionWidth {
            get {
                return ((int)(this["ResolutionWidth"]));
            }
            set {
                this["ResolutionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("768")]
        public int ResolutionHeight {
            get {
                return ((int)(this["ResolutionHeight"]));
            }
            set {
                this["ResolutionHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFullscreen {
            get {
                return ((bool)(this["IsFullscreen"]));
            }
            set {
                this["IsFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long SelectedStatsAccountSteamID {
            get {
                return ((long)(this["SelectedStatsAccountSteamID"]));
            }
            set {
                this["SelectedStatsAccountSteamID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPovDemos {
            get {
                return ((bool)(this["ShowPovDemos"]));
            }
            set {
                this["ShowPovDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEbotDemos {
            get {
                return ((bool)(this["ShowEbotDemos"]));
            }
            set {
                this["ShowEbotDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEseaDemos {
            get {
                return ((bool)(this["ShowEseaDemos"]));
            }
            set {
                this["ShowEseaDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowValveDemos {
            get {
                return ((bool)(this["ShowValveDemos"]));
            }
            set {
                this["ShowValveDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDateColumn {
            get {
                return ((bool)(this["ShowDateColumn"]));
            }
            set {
                this["ShowDateColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBombPlantedColumn {
            get {
                return ((bool)(this["ShowBombPlantedColumn"]));
            }
            set {
                this["ShowBombPlantedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBombDefusedColumn {
            get {
                return ((bool)(this["ShowBombDefusedColumn"]));
            }
            set {
                this["ShowBombDefusedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDemoNameColumn {
            get {
                return ((bool)(this["ShowDemoNameColumn"]));
            }
            set {
                this["ShowDemoNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMapNameColumn {
            get {
                return ((bool)(this["ShowMapNameColumn"]));
            }
            set {
                this["ShowMapNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTeam1NameColumn {
            get {
                return ((bool)(this["ShowTeam1NameColumn"]));
            }
            set {
                this["ShowTeam1NameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTeam2NameColumn {
            get {
                return ((bool)(this["ShowTeam2NameColumn"]));
            }
            set {
                this["ShowTeam2NameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowScoreTeam1Column {
            get {
                return ((bool)(this["ShowScoreTeam1Column"]));
            }
            set {
                this["ShowScoreTeam1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowScoreTeam2Column {
            get {
                return ((bool)(this["ShowScoreTeam2Column"]));
            }
            set {
                this["ShowScoreTeam2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHostnameColumn {
            get {
                return ((bool)(this["ShowHostnameColumn"]));
            }
            set {
                this["ShowHostnameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClientnameColumn {
            get {
                return ((bool)(this["ShowClientnameColumn"]));
            }
            set {
                this["ShowClientnameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDemoTypeColumn {
            get {
                return ((bool)(this["ShowDemoTypeColumn"]));
            }
            set {
                this["ShowDemoTypeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTickrateColumn {
            get {
                return ((bool)(this["ShowTickrateColumn"]));
            }
            set {
                this["ShowTickrateColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOneKillColumn {
            get {
                return ((bool)(this["ShowOneKillColumn"]));
            }
            set {
                this["ShowOneKillColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTwoKillsColumn {
            get {
                return ((bool)(this["ShowTwoKillsColumn"]));
            }
            set {
                this["ShowTwoKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowThreeKillsColumn {
            get {
                return ((bool)(this["ShowThreeKillsColumn"]));
            }
            set {
                this["ShowThreeKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFourKillsColumn {
            get {
                return ((bool)(this["ShowFourKillsColumn"]));
            }
            set {
                this["ShowFourKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFiveKillsColumn {
            get {
                return ((bool)(this["ShowFiveKillsColumn"]));
            }
            set {
                this["ShowFiveKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTotalKillsColumn {
            get {
                return ((bool)(this["ShowTotalKillsColumn"]));
            }
            set {
                this["ShowTotalKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBombExplodedColumn {
            get {
                return ((bool)(this["ShowBombExplodedColumn"]));
            }
            set {
                this["ShowBombExplodedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDeathsColumn {
            get {
                return ((bool)(this["ShowDeathsColumn"]));
            }
            set {
                this["ShowDeathsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAssistsColumn {
            get {
                return ((bool)(this["ShowAssistsColumn"]));
            }
            set {
                this["ShowAssistsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowKdColumn {
            get {
                return ((bool)(this["ShowKdColumn"]));
            }
            set {
                this["ShowKdColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHsColumn {
            get {
                return ((bool)(this["ShowHsColumn"]));
            }
            set {
                this["ShowHsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTkColumn {
            get {
                return ((bool)(this["ShowTkColumn"]));
            }
            set {
                this["ShowTkColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEkColumn {
            get {
                return ((bool)(this["ShowEkColumn"]));
            }
            set {
                this["ShowEkColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMvpColumn {
            get {
                return ((bool)(this["ShowMvpColumn"]));
            }
            set {
                this["ShowMvpColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPlayerScoreColumn {
            get {
                return ((bool)(this["ShowPlayerScoreColumn"]));
            }
            set {
                this["ShowPlayerScoreColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v1Column {
            get {
                return ((bool)(this["ShowClutch1v1Column"]));
            }
            set {
                this["ShowClutch1v1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v2Column {
            get {
                return ((bool)(this["ShowClutch1v2Column"]));
            }
            set {
                this["ShowClutch1v2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v3Column {
            get {
                return ((bool)(this["ShowClutch1v3Column"]));
            }
            set {
                this["ShowClutch1v3Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v4Column {
            get {
                return ((bool)(this["ShowClutch1v4Column"]));
            }
            set {
                this["ShowClutch1v4Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v5Column {
            get {
                return ((bool)(this["ShowClutch1v5Column"]));
            }
            set {
                this["ShowClutch1v5Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStartMoneyTeam1Column {
            get {
                return ((bool)(this["ShowStartMoneyTeam1Column"]));
            }
            set {
                this["ShowStartMoneyTeam1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStartMoneyTeam2Column {
            get {
                return ((bool)(this["ShowStartMoneyTeam2Column"]));
            }
            set {
                this["ShowStartMoneyTeam2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEquipementValueTeam1Column {
            get {
                return ((bool)(this["ShowEquipementValueTeam1Column"]));
            }
            set {
                this["ShowEquipementValueTeam1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEquipementValueTeam2Column {
            get {
                return ((bool)(this["ShowEquipementValueTeam2Column"]));
            }
            set {
                this["ShowEquipementValueTeam2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTickColumn {
            get {
                return ((bool)(this["ShowTickColumn"]));
            }
            set {
                this["ShowTickColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWinnerClanNameColumn {
            get {
                return ((bool)(this["ShowWinnerClanNameColumn"]));
            }
            set {
                this["ShowWinnerClanNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWinColumn {
            get {
                return ((bool)(this["ShowWinColumn"]));
            }
            set {
                this["ShowWinColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWinnerSideColumn {
            get {
                return ((bool)(this["ShowWinnerSideColumn"]));
            }
            set {
                this["ShowWinnerSideColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DateFormatEuropean {
            get {
                return ((bool)(this["DateFormatEuropean"]));
            }
            set {
                this["DateFormatEuropean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOldDemos {
            get {
                return ((bool)(this["ShowOldDemos"]));
            }
            set {
                this["ShowOldDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFaceitDemos {
            get {
                return ((bool)(this["ShowFaceitDemos"]));
            }
            set {
                this["ShowFaceitDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDurationColumn {
            get {
                return ((bool)(this["ShowDurationColumn"]));
            }
            set {
                this["ShowDurationColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFramerateColumn {
            get {
                return ((bool)(this["ShowFramerateColumn"]));
            }
            set {
                this["ShowFramerateColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCevoDemos {
            get {
                return ((bool)(this["ShowCevoDemos"]));
            }
            set {
                this["ShowCevoDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCommentColumn {
            get {
                return ((bool)(this["ShowCommentColumn"]));
            }
            set {
                this["ShowCommentColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutchCountColumn {
            get {
                return ((bool)(this["ShowClutchCountColumn"]));
            }
            set {
                this["ShowClutchCountColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LaunchParameters {
            get {
                return ((string)(this["LaunchParameters"]));
            }
            set {
                this["LaunchParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTotalDamageHealthColumn {
            get {
                return ((bool)(this["ShowTotalDamageHealthColumn"]));
            }
            set {
                this["ShowTotalDamageHealthColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTotalDamageArmorColumn {
            get {
                return ((bool)(this["ShowTotalDamageArmorColumn"]));
            }
            set {
                this["ShowTotalDamageArmorColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAverageDamageColumn {
            get {
                return ((bool)(this["ShowAverageDamageColumn"]));
            }
            set {
                this["ShowAverageDamageColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBanColumns {
            get {
                return ((bool)(this["ShowBanColumns"]));
            }
            set {
                this["ShowBanColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableHlae {
            get {
                return ((bool)(this["EnableHlae"]));
            }
            set {
                this["EnableHlae"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CsgoExePath {
            get {
                return ((string)(this["CsgoExePath"]));
            }
            set {
                this["CsgoExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLeftPartDetails {
            get {
                return ((bool)(this["ShowLeftPartDetails"]));
            }
            set {
                this["ShowLeftPartDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowAllAccounts {
            get {
                return ((bool)(this["IsShowAllAccounts"]));
            }
            set {
                this["IsShowAllAccounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowAllPlayers {
            get {
                return ((bool)(this["IsShowAllPlayers"]));
            }
            set {
                this["IsShowAllPlayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long WatchAccountSteamId {
            get {
                return ((long)(this["WatchAccountSteamId"]));
            }
            set {
                this["WatchAccountSteamId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOnlyBannedSuspects {
            get {
                return ((bool)(this["ShowOnlyBannedSuspects"]));
            }
            set {
                this["ShowOnlyBannedSuspects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowKillPerRoundColumn {
            get {
                return ((bool)(this["ShowKillPerRoundColumn"]));
            }
            set {
                this["ShowKillPerRoundColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAssistPerRoundColumn {
            get {
                return ((bool)(this["ShowAssistPerRoundColumn"]));
            }
            set {
                this["ShowAssistPerRoundColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDeathPerRoundColumn {
            get {
                return ((bool)(this["ShowDeathPerRoundColumn"]));
            }
            set {
                this["ShowDeathPerRoundColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRoundTypeColumn {
            get {
                return ((bool)(this["ShowRoundTypeColumn"]));
            }
            set {
                this["ShowRoundTypeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSideTroubleColumn {
            get {
                return ((bool)(this["ShowSideTroubleColumn"]));
            }
            set {
                this["ShowSideTroubleColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTeamTroubleColumn {
            get {
                return ((bool)(this["ShowTeamTroubleColumn"]));
            }
            set {
                this["ShowTeamTroubleColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPopFlashDemos {
            get {
                return ((bool)(this["ShowPopFlashDemos"]));
            }
            set {
                this["ShowPopFlashDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LimitStatsFolder {
            get {
                return ((bool)(this["LimitStatsFolder"]));
            }
            set {
                this["LimitStatsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowJumpKillCoulmn {
            get {
                return ((bool)(this["ShowJumpKillCoulmn"]));
            }
            set {
                this["ShowJumpKillCoulmn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogOnlyKillOnOverview {
            get {
                return ((bool)(this["LogOnlyKillOnOverview"]));
            }
            set {
                this["LogOnlyKillOnOverview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCrouchKillsColumn {
            get {
                return ((bool)(this["ShowCrouchKillsColumn"]));
            }
            set {
                this["ShowCrouchKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTicksColumn {
            get {
                return ((bool)(this["ShowTicksColumn"]));
            }
            set {
                this["ShowTicksColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2011-11-30")]
        public global::System.DateTime DateStatsFrom {
            get {
                return ((global::System.DateTime)(this["DateStatsFrom"]));
            }
            set {
                this["DateStatsFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateStatsTo {
            get {
                return ((global::System.DateTime)(this["DateStatsTo"]));
            }
            set {
                this["DateStatsTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTradeKillColumn {
            get {
                return ((bool)(this["ShowTradeKillColumn"]));
            }
            set {
                this["ShowTradeKillColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTradeDeathColumn {
            get {
                return ((bool)(this["ShowTradeDeathColumn"]));
            }
            set {
                this["ShowTradeDeathColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadFolder {
            get {
                return ((string)(this["DownloadFolder"]));
            }
            set {
                this["DownloadFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEseaRwsColumn {
            get {
                return ((bool)(this["ShowEseaRwsColumn"]));
            }
            set {
                this["ShowEseaRwsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowRoundPlayedColumn {
            get {
                return ((bool)(this["ShowRoundPlayedColumn"]));
            }
            set {
                this["ShowRoundPlayedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreLaterBan {
            get {
                return ((bool)(this["IgnoreLaterBan"]));
            }
            set {
                this["IgnoreLaterBan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseBotOnExit {
            get {
                return ((bool)(this["CloseBotOnExit"]));
            }
            set {
                this["CloseBotOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartBotOnLaunch {
            get {
                return ((bool)(this["StartBotOnLaunch"]));
            }
            set {
                this["StartBotOnLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOnlyAccountDemos {
            get {
                return ((bool)(this["ShowOnlyAccountDemos"]));
            }
            set {
                this["ShowOnlyAccountDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCustomActionsGeneration {
            get {
                return ((bool)(this["UseCustomActionsGeneration"]));
            }
            set {
                this["UseCustomActionsGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskThirdPartyConfirmation {
            get {
                return ((bool)(this["AskThirdPartyConfirmation"]));
            }
            set {
                this["AskThirdPartyConfirmation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HlaeConfigParentFolderPath {
            get {
                return ((string)(this["HlaeConfigParentFolderPath"]));
            }
            set {
                this["HlaeConfigParentFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableHlaeConfigParent {
            get {
                return ((bool)(this["EnableHlaeConfigParent"]));
            }
            set {
                this["EnableHlaeConfigParent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCtTeamName {
            get {
                return ((bool)(this["ShowCtTeamName"]));
            }
            set {
                this["ShowCtTeamName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTteamName {
            get {
                return ((bool)(this["ShowTteamName"]));
            }
            set {
                this["ShowTteamName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DemosListSize {
            get {
                return ((int)(this["DemosListSize"]));
            }
            set {
                this["DemosListSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTimeDeathColumn {
            get {
                return ((bool)(this["ShowTimeDeathColumn"]));
            }
            set {
                this["ShowTimeDeathColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RawFilesFolderDestination {
            get {
                return ((string)(this["RawFilesFolderDestination"]));
            }
            set {
                this["RawFilesFolderDestination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MovieOutputFileFolderDestination {
            get {
                return ((string)(this["MovieOutputFileFolderDestination"]));
            }
            set {
                this["MovieOutputFileFolderDestination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int MovieFramerate {
            get {
                return ((int)(this["MovieFramerate"]));
            }
            set {
                this["MovieFramerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MovieUserCfg {
            get {
                return ((string)(this["MovieUserCfg"]));
            }
            set {
                this["MovieUserCfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MovieShowDefaultCfg {
            get {
                return ((bool)(this["MovieShowDefaultCfg"]));
            }
            set {
                this["MovieShowDefaultCfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MovieAutoCloseGame {
            get {
                return ((bool)(this["MovieAutoCloseGame"]));
            }
            set {
                this["MovieAutoCloseGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MovieCleanUpRawFiles {
            get {
                return ((bool)(this["MovieCleanUpRawFiles"]));
            }
            set {
                this["MovieCleanUpRawFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MovieGenerateVideoFile {
            get {
                return ((bool)(this["MovieGenerateVideoFile"]));
            }
            set {
                this["MovieGenerateVideoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int MovieWidth {
            get {
                return ((int)(this["MovieWidth"]));
            }
            set {
                this["MovieWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int MovieHeight {
            get {
                return ((int)(this["MovieHeight"]));
            }
            set {
                this["MovieHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MovieUseVirtualDub {
            get {
                return ((bool)(this["MovieUseVirtualDub"]));
            }
            set {
                this["MovieUseVirtualDub"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int MovieVideoQuality {
            get {
                return ((int)(this["MovieVideoQuality"]));
            }
            set {
                this["MovieVideoQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int MovieAudioBitrate {
            get {
                return ((int)(this["MovieAudioBitrate"]));
            }
            set {
                this["MovieAudioBitrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int MovieVideoFramerate {
            get {
                return ((int)(this["MovieVideoFramerate"]));
            }
            set {
                this["MovieVideoFramerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MovieOpenInExplorer {
            get {
                return ((bool)(this["MovieOpenInExplorer"]));
            }
            set {
                this["MovieOpenInExplorer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MovieHlaeConfigParentFolderPath {
            get {
                return ((string)(this["MovieHlaeConfigParentFolderPath"]));
            }
            set {
                this["MovieHlaeConfigParentFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MovieEnableHlaeConfigParent {
            get {
                return ((bool)(this["MovieEnableHlaeConfigParent"]));
            }
            set {
                this["MovieEnableHlaeConfigParent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MovieShowDemoComment {
            get {
                return ((bool)(this["MovieShowDemoComment"]));
            }
            set {
                this["MovieShowDemoComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MovieCsgoExePath {
            get {
                return ((string)(this["MovieCsgoExePath"]));
            }
            set {
                this["MovieCsgoExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSimpleRadar {
            get {
                return ((bool)(this["UseSimpleRadar"]));
            }
            set {
                this["UseSimpleRadar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float MovieDeathNoticesDisplayTime {
            get {
                return ((float)(this["MovieDeathNoticesDisplayTime"]));
            }
            set {
                this["MovieDeathNoticesDisplayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsWorldwideEnabled {
            get {
                return ((bool)(this["IsWorldwideEnabled"]));
            }
            set {
                this["IsWorldwideEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MovieFullscreen {
            get {
                return ((bool)(this["MovieFullscreen"]));
            }
            set {
                this["MovieFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxConcurrentAnalyzes {
            get {
                return ((int)(this["MaxConcurrentAnalyzes"]));
            }
            set {
                this["MaxConcurrentAnalyzes"] = value;
            }
        }
    }
}
