import { defineConfig } from 'oxfmt';

export default defineConfig({
  singleQuote: true,
  printWidth: 120,
  ignorePatterns: [
    'node_modules',
    'package-lock.json',
    '.npmrc',
    'build',
    'build-assets',
    'out',
    'output',
    'dist',
    'static',
    '.DS_Store',
    '.*ignore',
    '.gitattributes',
    '.gitmodules',
    '*.png',
    '*.jpg',
    '.env*',
    'LICENSE',
    '*.dem',
    '*.info',
    '*.vdm',
    '*.log',
    '*.sh',
    '*.snap',
    '*.data',
    '*.po',
    '*.ai',
    '*.bat',
    '*.woff2',
    '*.cpp',
    '*.gyp',
    '.node-version',
    'cs2-server-plugin',
    'csgo-server-plugin',
  ],
});
