nodeLinker: hoisted
minimumReleaseAge: 1440

packages:
  - src/node/os/get-running-process-exit-code

allowBuilds:
  electron-winstaller: true
  esbuild: true
  registry-js: true
  '@akiver/cs-demo-analyzer': true

catalog:
  esbuild: 0.28.1
  node-gyp: 13.0.1
  vite: npm:@voidzero-dev/vite-plus-core@0.2.3
  vitest: 4.1.10

overrides:
  esbuild: 'catalog:'
  node-gyp: 'catalog:'
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

minimumReleaseAgeExclude:
  - '@akiver/cs-demo-analyzer'
