import { createReadStream } from 'node:fs';
import { pipeline } from 'node:stream/promises';
import { from as copyFrom } from 'pg-copy-streams';
import { getIngestionPool } from 'csdm/node/database/database';
import type { Database } from 'csdm/node/database/schema';

type Options<Table> = {
  csvFilePath: string;
  tableName: keyof Database;
  columns: Array<keyof Table>;
};

// Streams a CSV file into a table using the COPY protocol.
// It's the same command that "psql \copy" runs, without requiring the psql binary: the file bytes
// are forwarded as-is to the server, there is no parsing on the JS side.
export async function copyCsvIntoTable<Table>({ csvFilePath, tableName, columns }: Options<Table>) {
  const columnNames = columns.map((column) => `"${String(column)}"`).join(',');
  const client = await getIngestionPool().connect();

  try {
    // Match insertion writes hundreds of thousands of rows that can be re-generated by analyzing the
    // demo again, waiting for the WAL to be flushed on each commit is not worth the cost.
    await client.query('SET synchronous_commit = off');
    const stream = client.query(
      copyFrom(`COPY "${tableName}"(${columnNames}) FROM STDIN WITH (FORMAT csv, DELIMITER ',', ENCODING 'UTF8')`),
    );
    await pipeline(createReadStream(csvFilePath), stream);
  } finally {
    client.release();
  }
}
