import { types, Pool, type PoolClient } from 'pg';
import type { KyselyConfig, LogEvent, Logger } from 'kysely';
import { Kysely, PostgresDialect } from 'kysely';
import type { DatabaseSettings } from 'csdm/node/settings/settings';
import type { Database } from './schema';

export let db: Kysely<Database>;

let connectedSettings: DatabaseSettings | undefined;
let ingestionPool: Pool | undefined;
const ingestionClients = new Set<PoolClient>();

// Convert int8 values that are "safe" JS integers into Numbers otherwise leave them as strings.
// Postgres returns int8 values for int8 columns but also aggregate functions (COUNT(), SUM()...).
// By default node-pg parses int8 values into strings.
// We do this conversion for the following reasons:
// - The only int8 columns in the app are used for tables PK ID and we don't do Math operations on them.
// - To not have to think about casting values into numbers when using aggregate functions, i.e.:
//   db.count('id') vs db.raw('COUNT(id)::INT')
// - Sending BigInts through WebSocket result in strings.
types.setTypeParser(types.builtins.INT8, (value) => {
  const valueAsNumber = Number(value);
  if (Number.isSafeInteger(valueAsNumber)) {
    return valueAsNumber;
  }

  return value;
});
// Cast numeric types into JS Number so SUM, AVG... will be numbers instead of strings.
types.setTypeParser(types.builtins.NUMERIC, Number);
types.setTypeParser(types.builtins.INT4, Number);
types.setTypeParser(types.builtins.INT2, Number);

export function createDatabaseConnection(settings: DatabaseSettings) {
  const dialect = new PostgresDialect({
    pool: new Pool({
      host: settings.hostname,
      port: settings.port,
      user: settings.username,
      password: settings.password,
      database: settings.database,
      connectionTimeoutMillis: 10000,
    }),
  });

  let loggerFunction: Logger;
  if (process.env.LOG_DATABASE_QUERIES) {
    loggerFunction = (event: LogEvent) => {
      logger.log(event.query.sql);
      logger.log(event.query.parameters);
      if (event.level === 'error') {
        logger.log('Failed query:');
        logger.error(event.error);
      }
    };
  } else {
    loggerFunction = (event: LogEvent) => {
      if (event.level === 'error') {
        logger.log('Failed query:');
        logger.error(event.error);
      }
    };
  }

  const config: KyselyConfig = {
    dialect,
    log: loggerFunction,
  };

  // ! The ingestion pool is built from these settings, it must not survive a reconnection to another
  // server, otherwise match insertion would keep writing to the previous one.
  const previousIngestionPool = ingestionPool;
  ingestionPool = undefined;
  previousIngestionPool?.end().catch((error: unknown) => {
    logger.error('Failed to close the previous ingestion pool');
    logger.error(error);
  });

  connectedSettings = settings;
  db = new Kysely<Database>(config);
}

// The settings the app is currently connected with.
// They are not necessarily the ones stored in the settings file: connectDatabase() also accepts the
// settings coming from the connection form, which are persisted only once the connection succeeded.
function getConnectedDatabaseSettings(): DatabaseSettings {
  if (connectedSettings === undefined) {
    throw new Error('The database is not connected');
  }

  return connectedSettings;
}

// Dedicated pool for match insertion.
// It's separated from the Kysely pool because a match insertion sends dozens of concurrent COPY
// commands (see insert-match.ts) and each of them holds its connection until the whole CSV file has
// been streamed. Sharing the Kysely pool would starve the app queries and, worse, the queued
// acquisitions would be rejected by its connectionTimeoutMillis, which also applies to the time
// spent waiting in the pool queue.
function getIngestionPool(): Pool {
  if (ingestionPool === undefined) {
    const settings = getConnectedDatabaseSettings();
    ingestionPool = new Pool({
      host: settings.hostname,
      port: settings.port,
      user: settings.username,
      password: settings.password,
      database: settings.database,
      max: 8,
      // COPY commands may take minutes, waiting for a free connection must not time out.
      connectionTimeoutMillis: 0,
      // Match insertion writes hundreds of thousands of rows that can be re-generated by analyzing
      // the demo again, waiting for the WAL to be flushed on each commit is not worth the cost.
      // Set on the pool rather than per COPY: it's a session setting, it would be redundant.
      options: '-c synchronous_commit=off',
    });
  }

  return ingestionPool;
}

// Checked-out clients are tracked so that disconnecting can abort the COPY commands still running on
// them, see destroyDatabaseConnection().
export async function acquireIngestionClient(): Promise<PoolClient> {
  const client = await getIngestionPool().connect();
  ingestionClients.add(client);

  return client;
}

export function releaseIngestionClient(client: PoolClient) {
  // Already destroyed by destroyDatabaseConnection(), releasing it again would throw.
  if (!ingestionClients.delete(client)) {
    return;
  }

  client.release();
}

export async function destroyDatabaseConnection() {
  const pool = ingestionPool;
  ingestionPool = undefined;
  connectedSettings = undefined;

  // ! Disconnecting must not wait for an in-flight COPY to finish, which can take minutes on a demo
  // with positions: pool.end() only resolves once every checked-out client is back. Releasing them
  // with an error destroys their connection instead, which aborts the COPY server-side.
  for (const client of ingestionClients) {
    client.release(new Error('The database connection has been closed'));
  }
  ingestionClients.clear();

  await Promise.all([db?.destroy(), pool?.end()]);
}
