//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap avatar {
            get {
                object obj = ResourceManager.GetObject("avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cevo {
            get {
                object obj = ResourceManager.GetObject("cevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ebot {
            get {
                object obj = ResourceManager.GetObject("ebot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo01 {
            get {
                object obj = ResourceManager.GetObject("elo01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo02 {
            get {
                object obj = ResourceManager.GetObject("elo02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo03 {
            get {
                object obj = ResourceManager.GetObject("elo03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo04 {
            get {
                object obj = ResourceManager.GetObject("elo04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo05 {
            get {
                object obj = ResourceManager.GetObject("elo05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo06 {
            get {
                object obj = ResourceManager.GetObject("elo06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo07 {
            get {
                object obj = ResourceManager.GetObject("elo07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo08 {
            get {
                object obj = ResourceManager.GetObject("elo08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo09 {
            get {
                object obj = ResourceManager.GetObject("elo09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo10 {
            get {
                object obj = ResourceManager.GetObject("elo10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo11 {
            get {
                object obj = ResourceManager.GetObject("elo11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo12 {
            get {
                object obj = ResourceManager.GetObject("elo12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo13 {
            get {
                object obj = ResourceManager.GetObject("elo13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo14 {
            get {
                object obj = ResourceManager.GetObject("elo14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo15 {
            get {
                object obj = ResourceManager.GetObject("elo15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo16 {
            get {
                object obj = ResourceManager.GetObject("elo16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo17 {
            get {
                object obj = ResourceManager.GetObject("elo17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elo18 {
            get {
                object obj = ResourceManager.GetObject("elo18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap esea {
            get {
                object obj = ResourceManager.GetObject("esea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap esl {
            get {
                object obj = ResourceManager.GetObject("esl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap faceit {
            get {
                object obj = ResourceManager.GetObject("faceit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_rank {
            get {
                object obj = ResourceManager.GetObject("no_rank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap popflash {
            get {
                object obj = ResourceManager.GetObject("popflash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pov {
            get {
                object obj = ResourceManager.GetObject("pov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pugsetup {
            get {
                object obj = ResourceManager.GetObject("pugsetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Rank0 {
            get {
                return ResourceManager.GetString("Rank0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver I.
        /// </summary>
        internal static string Rank1 {
            get {
                return ResourceManager.GetString("Rank1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Nova Master.
        /// </summary>
        internal static string Rank10 {
            get {
                return ResourceManager.GetString("Rank10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Guardian I.
        /// </summary>
        internal static string Rank11 {
            get {
                return ResourceManager.GetString("Rank11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Guardian II.
        /// </summary>
        internal static string Rank12 {
            get {
                return ResourceManager.GetString("Rank12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Guardian Elite.
        /// </summary>
        internal static string Rank13 {
            get {
                return ResourceManager.GetString("Rank13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguished Master Guardian.
        /// </summary>
        internal static string Rank14 {
            get {
                return ResourceManager.GetString("Rank14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary Eagle.
        /// </summary>
        internal static string Rank15 {
            get {
                return ResourceManager.GetString("Rank15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary Eagle Master.
        /// </summary>
        internal static string Rank16 {
            get {
                return ResourceManager.GetString("Rank16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supreme Master First Class.
        /// </summary>
        internal static string Rank17 {
            get {
                return ResourceManager.GetString("Rank17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Elite.
        /// </summary>
        internal static string Rank18 {
            get {
                return ResourceManager.GetString("Rank18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver II.
        /// </summary>
        internal static string Rank2 {
            get {
                return ResourceManager.GetString("Rank2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver III.
        /// </summary>
        internal static string Rank3 {
            get {
                return ResourceManager.GetString("Rank3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver IV.
        /// </summary>
        internal static string Rank4 {
            get {
                return ResourceManager.GetString("Rank4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Elite.
        /// </summary>
        internal static string Rank5 {
            get {
                return ResourceManager.GetString("Rank5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Elite Master.
        /// </summary>
        internal static string Rank6 {
            get {
                return ResourceManager.GetString("Rank6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Nova I.
        /// </summary>
        internal static string Rank7 {
            get {
                return ResourceManager.GetString("Rank7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Nova II.
        /// </summary>
        internal static string Rank8 {
            get {
                return ResourceManager.GetString("Rank8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Nova III.
        /// </summary>
        internal static string Rank9 {
            get {
                return ResourceManager.GetString("Rank9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap valve {
            get {
                object obj = ResourceManager.GetObject("valve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wanmei {
            get {
                object obj = ResourceManager.GetObject("wanmei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
