import { Game } from 'csdm/common/types/counter-strike';
import type { InsertableMap } from './map-table';

export function getDefaultMaps(game?: Game) {
  const csgoMaps: InsertableMap[] = [
    {
      name: 'cs_assault',
      game: Game.CSGO,
      position_x: 4041,
      position_y: 7838,
      scale: 4.6,
      threshold_z: 0,
    },
    {
      name: 'cs_italy',
      game: Game.CSGO,
      position_x: -2647,
      position_y: 2592,
      scale: 4.6,
      threshold_z: 0,
    },
    {
      name: 'cs_militia',
      game: Game.CSGO,
      position_x: -1474,
      position_y: 2296,
      scale: 4.5,
      threshold_z: 25,
    },
    {
      name: 'cs_office',
      game: Game.CSGO,
      position_x: -1838,
      position_y: 1858,
      scale: 4.1,
      threshold_z: 0,
    },
    {
      name: 'de_ancient',
      game: Game.CSGO,
      position_x: -2953,
      position_y: 2164,
      scale: 5,
      threshold_z: 0,
    },
    {
      name: 'de_anubis',
      game: Game.CSGO,
      position_x: -2796,
      position_y: 3328,
      scale: 5.22,
      threshold_z: 0,
    },
    {
      name: 'de_aztec',
      game: Game.CSGO,
      position_x: -3200,
      position_y: 2841,
      scale: 6,
      threshold_z: 0,
    },
    {
      name: 'de_cache',
      game: Game.CSGO,
      position_x: -2000,
      position_y: 3250,
      scale: 5.5,
      threshold_z: 0,
    },
    {
      name: 'de_canals',
      game: Game.CSGO,
      position_x: -2496,
      position_y: 1792,
      scale: 4,
      threshold_z: 0,
    },
    {
      name: 'de_cbble',
      game: Game.CSGO,
      position_x: -3840,
      position_y: 3072,
      scale: 6,
      threshold_z: 0,
    },
    {
      name: 'de_dust',
      game: Game.CSGO,
      position_x: -2850,
      position_y: 4073,
      scale: 6,
      threshold_z: 0,
    },
    {
      name: 'de_dust2',
      game: Game.CSGO,
      position_x: -2476,
      position_y: 3239,
      scale: 4.4,
      threshold_z: 0,
    },
    {
      name: 'de_inferno',
      game: Game.CSGO,
      position_x: -2087,
      position_y: 3870,
      scale: 4.9,
      threshold_z: 0,
    },
    {
      name: 'de_mirage',
      game: Game.CSGO,
      position_x: -3230,
      position_y: 1713,
      scale: 5,
      threshold_z: 0,
    },
    {
      name: 'de_nuke',
      game: Game.CSGO,
      position_x: -3453,
      position_y: 2887,
      scale: 7,
      threshold_z: -495,
    },
    {
      name: 'de_overpass',
      game: Game.CSGO,
      position_x: -4831,
      position_y: 1781,
      scale: 5.2,
      threshold_z: 0,
    },
    {
      name: 'de_train',
      game: Game.CSGO,
      position_x: -2477,
      position_y: 2392,
      scale: 4.7,
      threshold_z: 0,
    },
    {
      name: 'de_vertigo',
      game: Game.CSGO,
      position_x: -3168,
      position_y: 1762,
      scale: 4,
      threshold_z: 11700,
    },
  ];

  const cs2Maps: InsertableMap[] = [
    {
      name: 'cs_agency',
      game: Game.CS2,
      position_x: -2597,
      position_y: 2079,
      scale: 4.1817436,
      threshold_z: 0,
    },
    {
      name: 'cs_assault',
      game: Game.CS2,
      position_x: 4041,
      position_y: 7838,
      scale: 4.6,
      threshold_z: 0,
    },
    {
      name: 'cs_italy',
      game: Game.CS2,
      position_x: -2647,
      position_y: 2592,
      scale: 4.6,
      threshold_z: 0,
    },
    {
      name: 'cs_militia',
      game: Game.CS2,
      position_x: -1474,
      position_y: 2296,
      scale: 4.5,
      threshold_z: 25,
    },
    {
      name: 'cs_office',
      game: Game.CS2,
      position_x: -1838,
      position_y: 1858,
      scale: 4.1,
      threshold_z: 0,
    },
    {
      name: 'de_ancient',
      game: Game.CS2,
      position_x: -2953,
      position_y: 2164,
      scale: 5,
      threshold_z: 0,
    },
    {
      name: 'de_anubis',
      game: Game.CS2,
      position_x: -2796,
      position_y: 3328,
      scale: 5.22,
      threshold_z: 0,
    },
    {
      name: 'de_assembly',
      game: Game.CS2,
      position_x: 1628,
      position_y: 4512,
      scale: 2.84,
      threshold_z: 0,
    },
    {
      name: 'de_aztec',
      game: Game.CS2,
      position_x: -3200,
      position_y: 2841,
      scale: 6,
      threshold_z: 0,
    },
    {
      name: 'de_basalt',
      game: Game.CS2,
      position_x: -2345,
      position_y: 2391,
      scale: 4.37,
      threshold_z: 0,
    },
    {
      name: 'de_brewery',
      game: Game.CS2,
      position_x: -4122,
      position_y: 4394,
      scale: 2.1820312,
      threshold_z: 0,
    },
    {
      name: 'de_cache',
      game: Game.CS2,
      position_x: -2000,
      position_y: 3250,
      scale: 5.5,
      threshold_z: 0,
    },
    {
      name: 'de_canals',
      game: Game.CS2,
      position_x: -2496,
      position_y: 1792,
      scale: 4,
      threshold_z: 0,
    },
    {
      name: 'de_cbble',
      game: Game.CS2,
      position_x: -3840,
      position_y: 3072,
      scale: 6,
      threshold_z: 0,
    },
    {
      name: 'de_dogtown',
      game: Game.CS2,
      position_x: -1741,
      position_y: 3295,
      scale: 2.0323243,
      threshold_z: 0,
    },
    {
      name: 'de_dust',
      game: Game.CS2,
      position_x: -2850,
      position_y: 4073,
      scale: 6,
      threshold_z: 0,
    },
    {
      name: 'de_dust2',
      game: Game.CS2,
      position_x: -2476,
      position_y: 3239,
      scale: 4.4,
      threshold_z: 0,
    },
    {
      name: 'de_edin',
      game: Game.CS2,
      position_x: -383,
      position_y: 4420,
      scale: 4.803717,
      threshold_z: 0,
    },
    {
      name: 'de_grail',
      game: Game.CS2,
      position_x: -4395,
      position_y: 4203,
      scale: 2.1756864,
      threshold_z: 0,
    },
    {
      name: 'de_inferno',
      game: Game.CS2,
      position_x: -2087,
      position_y: 3870,
      scale: 4.9,
      threshold_z: 0,
    },
    {
      name: 'de_jura',
      game: Game.CS2,
      position_x: -2126,
      position_y: 2389,
      scale: 2.504188,
      threshold_z: 0,
    },
    {
      name: 'de_memento',
      game: Game.CS2,
      position_x: -2111,
      position_y: 2534,
      scale: 3.9720395,
      threshold_z: 0,
    },
    {
      name: 'de_mills',
      game: Game.CS2,
      position_x: -4810,
      position_y: -320,
      scale: 5.148437,
      threshold_z: 0,
    },
    {
      name: 'de_mirage',
      game: Game.CS2,
      position_x: -3230,
      position_y: 1713,
      scale: 5,
      threshold_z: 0,
    },
    {
      name: 'de_nuke',
      game: Game.CS2,
      position_x: -3453,
      position_y: 2887,
      scale: 7,
      threshold_z: -495,
    },
    {
      name: 'de_overpass',
      game: Game.CS2,
      position_x: -4831,
      position_y: 1781,
      scale: 5.2,
      threshold_z: 0,
    },
    {
      name: 'de_palais',
      game: Game.CS2,
      position_x: -1353,
      position_y: 2044,
      scale: 2.8003397,
      threshold_z: 103,
    },
    {
      name: 'de_thera',
      game: Game.CS2,
      position_x: -85,
      position_y: 2261,
      scale: 4.846961,
      threshold_z: -4,
    },
    {
      name: 'de_train',
      game: Game.CS2,
      position_x: -2308,
      position_y: 2078,
      scale: 4.082077,
      threshold_z: 0,
    },
    {
      name: 'de_vertigo',
      game: Game.CS2,
      position_x: -3168,
      position_y: 1762,
      scale: 4,
      threshold_z: 11700,
    },
    {
      name: 'de_whistle',
      game: Game.CS2,
      position_x: -1825,
      position_y: 1104,
      scale: 2.8,
      threshold_z: 0,
    },
  ];

  switch (game) {
    case Game.CSGO:
      return csgoMaps;
    case Game.CS2:
      return cs2Maps;
    default:
      return [...csgoMaps, ...cs2Maps];
  }
}
