import path from 'node:path';
import net from 'node:net';
import { randomBytes } from 'node:crypto';
import fs from 'fs-extra';
import type { DatabaseConnectionSettings } from 'csdm/node/settings/settings';
import { isWindows } from 'csdm/node/os/is-windows';
import {
  type ExecutableName,
  getEmbeddedDatabaseDataFolderPath,
  getEmbeddedDatabaseFolderPath,
  getEmbeddedDatabasePasswordFilePath,
  getEmbeddedDatabaseLogFilePath,
  getEmbeddedPostgreSqlBinariesFolderPath,
  getEmbeddedPostgreSqlExecutablePath,
} from './embedded-postgresql-paths';
import { runEmbeddedPostgreSqlExecutable, type ExecutableResult } from './run-embedded-postgresql-executable';
import { EmbeddedDatabaseInitializationError } from './errors/embedded-database-initialization-error';
import { EmbeddedDatabaseStartError } from './errors/embedded-database-start-error';
import { EmbeddedDatabaseBinariesNotFoundError } from './errors/embedded-database-binaries-not-found-error';
import { EmbeddedDatabaseVersionMismatchError } from './errors/embedded-database-version-mismatch-error';
import { EMBEDDED_POSTGRESQL_MAJOR_VERSION } from './embedded-postgresql-version';
import { BaseError } from 'csdm/node/errors/base-error';

const DATABASE_USERNAME = 'csdm';
// Name of the config file written by the app in the data folder, included from postgresql.conf.
const EMBEDDED_POSTGRESQL_CONFIG_FILE_NAME = 'csdm.conf';
// Port used by the server, it's also part of the Unix socket file name.
const EMBEDDED_POSTGRESQL_SOCKET_PORT = 5432;

// Connection settings of the server started by this process, null when it has not been started or has been stopped.
let connectionSettings: DatabaseConnectionSettings | null = null;
let pendingStart: Promise<DatabaseConnectionSettings> | null = null;
let pendingStop: Promise<void> | null = null;
let pendingDeletion: Promise<void> | null = null;

async function assertBinariesInstalled() {
  const executables: ExecutableName[] = ['pg_ctl', 'initdb', 'postgres'];
  for (const executable of executables) {
    if (!(await fs.pathExists(getEmbeddedPostgreSqlExecutablePath(executable)))) {
      throw new EmbeddedDatabaseBinariesNotFoundError(getEmbeddedPostgreSqlBinariesFolderPath());
    }
  }
}

/**
 * Checks that a data folder can be opened by the bundled binaries from the content of its PG_VERSION file.
 * initdb writes the major version in it.
 */
function assertEmbeddedPostgreSqlVersion(pgVersionFileContent: string) {
  const content = pgVersionFileContent.trim();
  const majorVersion = Number.parseInt(content, 10);
  if (Number.isNaN(majorVersion)) {
    throw new EmbeddedDatabaseStartError(
      `the PG_VERSION file of the data folder is unreadable (content: "${content.slice(0, 32)}")`,
    );
  }

  if (majorVersion !== EMBEDDED_POSTGRESQL_MAJOR_VERSION) {
    throw new EmbeddedDatabaseVersionMismatchError(majorVersion, EMBEDDED_POSTGRESQL_MAJOR_VERSION);
  }
}

// Quoted strings in postgresql.conf follow C escaping rules: backslashes and single quotes must be escaped.
function quote(value: string) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

function buildEmbeddedPostgreSqlConfig(mode: EmbeddedPostgreSqlListenMode) {
  const settings: [string, string][] = [];
  if (mode.type === 'socket') {
    settings.push(['listen_addresses', quote('')]);
    settings.push(['port', String(EMBEDDED_POSTGRESQL_SOCKET_PORT)]);
    settings.push(['unix_socket_directories', quote(mode.folderPath)]);
  } else {
    settings.push(['listen_addresses', quote('127.0.0.1')]);
    settings.push(['port', String(mode.port)]);
    // Without it the server would also create a socket in /tmp on Unix, where it may conflict with a PostgreSQL server
    // installed on the machine.
    settings.push(['unix_socket_directories', quote('')]);
  }

  settings.push(
    // Everything the server logs goes to its stderr, which pg_ctl redirects to the log file given at start: one
    // file holds the whole session, from the pg_ctl output to the shutdown.
    ['logging_collector', 'off'],
    ['log_destination', quote('stderr')],
    // English messages regardless of the OS locale.
    ['lc_messages', quote('C')],
    // Not needed for the app's workload and the bundled binaries may not ship the JIT provider.
    ['jit', 'off'],
  );

  const lines = [
    '# Generated by CS Demo Manager every time the server starts, changes will be lost.',
    '# Custom settings must go in postgresql.conf instead.',
    ...settings.map(([name, value]) => `${name} = ${value}`),
  ];

  return `${lines.join('\n')}\n`;
}

type EmbeddedPostgreSqlListenMode =
  | {
      // Unix domain socket only, nothing is exposed on the network and the socket folder permissions restrict access
      // to the current user.
      type: 'socket';
      folderPath: string;
    }
  | {
      // TCP on the loopback interface, used on Windows where Unix sockets are not an option for the client, and as a
      // fallback when the socket path is too long.
      type: 'tcp';
      port: number;
    };

function getUnixSocketPath(folderPath: string) {
  return path.join(folderPath, `.s.PGSQL.${EMBEDDED_POSTGRESQL_SOCKET_PORT}`);
}

function canListenOnUnixSocket(folderPath: string) {
  if (isWindows) {
    return false;
  }

  // sun_path is limited to 104 bytes on macOS (108 on Linux), including the terminating null byte.
  const maxUnixSocketPathLength = 103;

  return Buffer.byteLength(getUnixSocketPath(folderPath), 'utf8') <= maxUnixSocketPathLength;
}

function runPgCtl(args: string[], options?: Parameters<typeof runEmbeddedPostgreSqlExecutable>[2]) {
  return runEmbeddedPostgreSqlExecutable(
    getEmbeddedPostgreSqlExecutablePath('pg_ctl'),
    ['-D', getEmbeddedDatabaseDataFolderPath(), ...args],
    options,
  );
}

async function isServerRunning() {
  // Exit codes: 0 when the server is running, 3 when it's not, 4 when the data folder doesn't exist.
  const { exitCode } = await runPgCtl(['status']);

  return exitCode === 0;
}

type StopMode = 'fast' | 'immediate';

function runPgCtlStop(mode: StopMode, timeoutInSeconds: number) {
  return runPgCtl(['stop', '-m', mode, '-w', '-t', String(timeoutInSeconds)]);
}

function formatStopFailure(mode: StopMode, result: ExecutableResult) {
  return `pg_ctl stop -m ${mode} exited with code ${result.exitCode}: ${result.output}`;
}

// Resolves once no stop or deletion is in flight, one may begin while another one completes.
// Their errors are not reported here: the caller acts on the resulting state.
async function waitForPendingStopAndDeletion() {
  while (pendingStop !== null || pendingDeletion !== null) {
    try {
      await (pendingDeletion ?? pendingStop);
    } catch {
      // Ignored, see above.
    }
  }
}

/**
 * Stops the server, throws if it's still running afterwards.
 * Fast shutdown first, escalating to immediate (no checkpoint, WAL recovery on next start) rather than leaving the
 * server behind.
 */
async function stopServer() {
  const fastResult = await runPgCtlStop('fast', 30);
  if (fastResult.exitCode === 0) {
    return;
  }

  if (!(await isServerRunning())) {
    logger.warn('The embedded database server was not running anymore');
    return;
  }

  logger.warn(formatStopFailure('fast', fastResult));
  logger.warn('Stopping the embedded database server in immediate mode');
  const immediateResult = await runPgCtlStop('immediate', 10);
  if (immediateResult.exitCode !== 0 && (await isServerRunning())) {
    throw new Error(formatStopFailure('immediate', immediateResult));
  }
}

// A server started by a previous daemon that could not stop it (killed on Windows, crashed…) may still hold the data
// folder, this process must own it before starting a server or deleting the data.
async function stopStrayServer(reason: string) {
  if (await isServerRunning()) {
    logger.warn(`An embedded database server is already running, stopping it ${reason}`);
    await stopServer();
  }
}

async function readPassword() {
  const filePath = getEmbeddedDatabasePasswordFilePath();
  try {
    const content = await fs.readFile(filePath, 'utf8');

    return content.trim();
  } catch (error) {
    throw new EmbeddedDatabaseStartError(`unable to read the password file ${filePath}`, error);
  }
}

async function initializeDataFolder(dataFolderPath: string) {
  logger.log('Initializing the embedded database data folder');
  const password = randomBytes(24).toString('base64url');
  const passwordFilePath = getEmbeddedDatabasePasswordFilePath();
  await fs.writeFile(passwordFilePath, `${password}\n`, { mode: 0o600 });

  const result = await runEmbeddedPostgreSqlExecutable(getEmbeddedPostgreSqlExecutablePath('initdb'), [
    '-D',
    dataFolderPath,
    '-U',
    DATABASE_USERNAME,
    '--encoding=UTF8',
    // The builtin collation provider is Unicode-aware and behaves the same on every OS, unlike the libc provider that
    // depends on the locales installed on the machine.
    '--locale-provider=builtin',
    '--builtin-locale=C.UTF-8',
    '--locale=C',
    // Unix socket connections are protected by the socket folder permissions, TCP ones require the password.
    '--auth-local=trust',
    '--auth-host=scram-sha-256',
    `--pwfile=${passwordFilePath}`,
    '--no-instructions',
  ]);
  if (result.exitCode !== 0) {
    // A partially initialized folder would be mistaken for a valid one on the next start.
    await fs.remove(dataFolderPath);
    throw new EmbeddedDatabaseInitializationError(result.output);
  }
}

// The config file generated by the app is included from postgresql.conf, at the end so that it takes precedence.
async function ensureConfigFileIncluded(dataFolderPath: string) {
  const postgresqlConfigPath = path.join(dataFolderPath, 'postgresql.conf');
  const includeLine = `include '${EMBEDDED_POSTGRESQL_CONFIG_FILE_NAME}'`;
  const content = await fs.readFile(postgresqlConfigPath, 'utf8');
  if (!content.includes(includeLine)) {
    await fs.appendFile(postgresqlConfigPath, `\n${includeLine}\n`);
  }
}

function findFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.unref();
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      server.close(() => {
        if (address !== null && typeof address === 'object') {
          resolve(address.port);
        } else {
          reject(new Error('Unable to find a free TCP port'));
        }
      });
    });
  });
}

async function resolveListenMode(): Promise<EmbeddedPostgreSqlListenMode> {
  const folderPath = getEmbeddedDatabaseFolderPath();
  if (canListenOnUnixSocket(folderPath)) {
    return { type: 'socket', folderPath };
  }

  if (!isWindows) {
    logger.warn(`The Unix socket path would be too long in ${folderPath}, listening on TCP instead`);
  }

  return { type: 'tcp', port: await findFreePort() };
}

function writeConfigFile(dataFolderPath: string, mode: EmbeddedPostgreSqlListenMode) {
  return fs.writeFile(
    path.join(dataFolderPath, EMBEDDED_POSTGRESQL_CONFIG_FILE_NAME),
    buildEmbeddedPostgreSqlConfig(mode),
  );
}

// The port found free by findFreePort() is released before the server binds it, another process may take it in
// between. The server then logs (in English due to lc_messages=C) "could not bind IPv4 address" followed by this
// fatal error that stops it.
function isPortInUseFailure(startFailure: string) {
  return startFailure.includes('could not create any TCP/IP sockets');
}

function buildConnectionSettings(mode: EmbeddedPostgreSqlListenMode, password: string) {
  const settings: DatabaseConnectionSettings = {
    // The pg module connects through a Unix socket when the host is a folder path.
    hostname: mode.type === 'socket' ? mode.folderPath : '127.0.0.1',
    port: mode.type === 'socket' ? EMBEDDED_POSTGRESQL_SOCKET_PORT : mode.port,
    username: DATABASE_USERNAME,
    database: 'csdm',
    password,
  };

  return settings;
}

async function readLogFile(filePath: string, exitCode: number | null) {
  const fallback = `pg_ctl start exited with code ${exitCode}`;
  try {
    const content = (await fs.readFile(filePath, 'utf8')).trim();

    return content === '' ? `${fallback} without any output` : content;
  } catch {
    return `${fallback}, the log file ${filePath} could not be read`;
  }
}

// pg_ctl appends to the log file: the previous session is kept aside for diagnosis so that the file only holds the
// session that starts.
async function rotateLogFile(logFilePath: string) {
  if (!(await fs.pathExists(logFilePath))) {
    return;
  }

  const { dir, name, ext } = path.parse(logFilePath);
  const previousLogFilePath = path.join(dir, `${name}.previous${ext}`);
  try {
    await fs.move(logFilePath, previousLogFilePath, { overwrite: true });
  } catch (error) {
    // The server can still start, the file just keeps growing until the next rotation.
    logger.warn(`Unable to rotate the embedded database log file ${logFilePath}`);
    logger.warn(error);
  }
}

/**
 * Runs pg_ctl start with the server output redirected to the log file.
 * Returns null when the server started, the content of the log file otherwise.
 */
async function startServer(logFilePath: string) {
  const startTimeoutInSeconds = 60;
  await rotateLogFile(logFilePath);
  // -w waits until the server accepts connections.
  // pg_ctl's stdout/stderr must be a file, not pipes: the server inherits them and keeps them open for its lifetime,
  // so with pipes the command would never complete. The server logs through the inherited file rather than -l because
  // on Windows cmd.exe cannot open a file this process already has open for writing.
  const result = await runPgCtl(['start', '-w', '-t', String(startTimeoutInSeconds)], {
    outputFilePath: logFilePath,
  });
  if (result.exitCode === 0) {
    return null;
  }

  return readLogFile(logFilePath, result.exitCode);
}

async function start(): Promise<DatabaseConnectionSettings> {
  await assertBinariesInstalled();

  const folderPath = getEmbeddedDatabaseFolderPath();
  const dataFolderPath = getEmbeddedDatabaseDataFolderPath();
  await fs.ensureDir(folderPath);
  if (!isWindows) {
    // The folder holds the Unix socket that accepts connections without password, it must be private to the user.
    await fs.chmod(folderPath, 0o700);
  }

  const pgVersionFilePath = path.join(dataFolderPath, 'PG_VERSION');
  if (!(await fs.pathExists(pgVersionFilePath))) {
    await initializeDataFolder(dataFolderPath);
  }

  const versionFileContent = await fs.readFile(pgVersionFilePath, 'utf8');
  assertEmbeddedPostgreSqlVersion(versionFileContent);

  // Its configuration may be outdated and its TCP port unknown, replace it.
  await stopStrayServer('to start one with the current configuration');

  let listenMode = await resolveListenMode();
  await ensureConfigFileIncluded(dataFolderPath);
  // Unix socket connections are trusted (auth-local=trust), the password is only sent over TCP.
  const password = listenMode.type === 'tcp' ? await readPassword() : '';
  const logFilePath = getEmbeddedDatabaseLogFilePath();

  // Bounded so that a machine where every port is taken as soon as it's found does not retry forever.
  const maxStartAttempts = 3;
  for (let attempt = 1; ; attempt++) {
    await writeConfigFile(dataFolderPath, listenMode);
    const description =
      listenMode.type === 'socket' ? `Unix socket in ${listenMode.folderPath}` : `TCP port ${listenMode.port}`;
    logger.log(`Starting the embedded database server, listening on ${description}`);
    const startFailure = await startServer(logFilePath);
    if (startFailure === null) {
      return buildConnectionSettings(listenMode, password);
    }

    if (listenMode.type !== 'tcp' || attempt >= maxStartAttempts || !isPortInUseFailure(startFailure)) {
      throw new EmbeddedDatabaseStartError(startFailure);
    }

    logger.warn(
      `The TCP port ${listenMode.port} was taken before the embedded database server could bind it, retrying with another one`,
    );
    listenMode = { type: 'tcp', port: await findFreePort() };
  }
}

/**
 * Starts the bundled PostgreSQL server if it's not already running and returns how to connect to it.
 * The data folder is created on first start.
 */
export async function startEmbeddedPostgreSql(): Promise<DatabaseConnectionSettings> {
  if (pendingStart !== null) {
    return pendingStart;
  }

  // Starting while a deletion is in progress would open a data folder that is being removed.
  await waitForPendingStopAndDeletion();

  if (connectionSettings !== null) {
    if (await isServerRunning()) {
      return connectionSettings;
    }

    logger.warn('The embedded database server is not running anymore, restarting it');
    connectionSettings = null;
    // A stop or a deletion may have begun during the status check.
    await waitForPendingStopAndDeletion();
  }

  // Another caller may have started the server while this one was waiting above.
  if (pendingStart !== null) {
    return pendingStart;
  }

  pendingStart = start()
    .then((settings) => {
      connectionSettings = settings;

      return settings;
    })
    .catch((error) => {
      if (error instanceof BaseError) {
        throw error;
      }

      throw new EmbeddedDatabaseStartError(error instanceof Error ? error.message : String(error), error);
    })
    .finally(() => {
      pendingStart = null;
    });

  return pendingStart;
}

/**
 * Stops the bundled PostgreSQL server, does nothing if this process didn't start it.
 */
export async function stopEmbeddedPostgreSql() {
  if (pendingStart !== null) {
    try {
      await pendingStart;
    } catch {
      // The start failed, there is nothing to stop.
    }
  }

  if (pendingStop !== null) {
    return pendingStop;
  }

  if (connectionSettings === null) {
    return;
  }

  pendingStop = stopAndForget().finally(() => {
    pendingStop = null;
  });

  return pendingStop;
}

async function stopAndForget() {
  logger.log('Stopping the embedded database server');
  await stopServer();
  connectionSettings = null;
}

async function deleteData() {
  await stopEmbeddedPostgreSql();
  await stopStrayServer('before deleting its data');

  logger.log('Deleting the embedded database data folder');
  await fs.remove(getEmbeddedDatabaseDataFolderPath());
  // The password belongs to the deleted cluster, a new one is generated with the next data folder.
  await fs.remove(getEmbeddedDatabasePasswordFilePath());
}

export async function deleteEmbeddedDatabaseData() {
  if (pendingDeletion !== null) {
    return pendingDeletion;
  }

  pendingDeletion = deleteData().finally(() => {
    pendingDeletion = null;
  });

  return pendingDeletion;
}
