import path from 'node:path';
import fs from 'fs-extra';
import { getClusterDataFolderPath } from './embedded-postgres-paths';

/**
 * postgresql.auto.conf has a higher precedence than postgresql.conf and is meant to be
 * machine-generated. The app never runs ALTER SYSTEM, which is the only other writer of this file.
 */
function buildPostgresqlConf(port: number) {
  const settings = [
    // ! Never listen on anything else than the loopback interface.
    `listen_addresses = '127.0.0.1'`,
    `port = ${port}`,
    `max_connections = 50`,
    `shared_buffers = 256MB`,
    `work_mem = 32MB`,
    `maintenance_work_mem = 256MB`,
    `max_wal_size = 4GB`,
    `checkpoint_timeout = 15min`,
  ];

  if (process.platform !== 'win32') {
    // Prevents colliding with the socket of a PostgreSQL instance installed on the system.
    settings.push(`unix_socket_directories = ''`);
  }

  return `# Generated by CS Demo Manager, manual changes are overwritten on each start.\n${settings.join('\n')}\n`;
}

const PG_HBA_CONF = `# Generated by CS Demo Manager, manual changes are overwritten on each start.
host all all 127.0.0.1/32 scram-sha-256
host all all ::1/128      scram-sha-256
`;

export async function writeClusterConfig(port: number) {
  const dataFolderPath = getClusterDataFolderPath();
  await Promise.all([
    fs.writeFile(path.join(dataFolderPath, 'postgresql.auto.conf'), buildPostgresqlConf(port)),
    fs.writeFile(path.join(dataFolderPath, 'pg_hba.conf'), PG_HBA_CONF),
  ]);
}
