import path from 'node:path';
import fs from 'fs-extra';
import { getClusterDataFolderPath } from './embedded-postgres-paths';

/**
 * postgresql.auto.conf has a higher precedence than postgresql.conf and is meant to be
 * machine-generated. The app never runs ALTER SYSTEM, which is the only other writer of this file.
 */
function buildPostgresqlConf(port: number) {
  const settings = [
    // ! Never listen on anything else than the loopback interface.
    `listen_addresses = '127.0.0.1'`,
    // ! The only channel for the port: pg_ctl is not given -o '-p'.
    `port = ${port}`,
  ];

  if (process.platform !== 'win32') {
    // Prevents colliding with the socket of a PostgreSQL instance installed on the system.
    settings.push(`unix_socket_directories = ''`);
  }

  return `# Generated by CS Demo Manager, manual changes are overwritten on each start.\n${settings.join('\n')}\n`;
}

/**
 * pg_hba.conf is left as initdb wrote it: `--auth scram-sha-256` already restricts every local
 * connection to a password, and listen_addresses above is what keeps the cluster off the network.
 */
export async function writeClusterConfig(port: number) {
  const dataFolderPath = getClusterDataFolderPath();
  await fs.writeFile(path.join(dataFolderPath, 'postgresql.auto.conf'), buildPostgresqlConf(port));
}
