import type { Generated, Selectable } from 'kysely';
import type { PlayerColor, Rank, RankType } from 'csdm/common/types/counter-strike';
import type { ColumnID } from 'csdm/common/types/column-id';

export type MatchPlayerTable = {
  id: Generated<ColumnID>;
  match_checksum: string;
  steam_id: string;
  index: number;
  name: string;
  kill_count: number;
  death_count: number;
  assist_count: number;
  kill_death_ratio: number;
  damage_health: number;
  damage_armor: number;
  average_damage_per_round: number;
  average_kill_per_round: number;
  average_death_per_round: number;
  utility_damage_per_round: number;
  headshot_count: number;
  headshot_percentage: number;
  first_kill_count: number;
  first_death_count: number;
  mvp_count: number;
  rank_type: RankType;
  rank: Rank;
  old_rank: Rank;
  wins_count: number;
  bomb_planted_count: number;
  bomb_defused_count: number;
  hostage_rescued_count: number;
  score: number;
  team_name: string;
  kast: number;
  utility_damage: number;
  trade_kill_count: number;
  trade_death_count: number;
  first_trade_kill_count: number;
  first_trade_death_count: number;
  one_kill_count: number;
  two_kill_count: number;
  three_kill_count: number;
  four_kill_count: number;
  five_kill_count: number;
  hltv_rating: number;
  hltv_rating_2: number;
  crosshair_share_code: string;
  color: PlayerColor;
  inspect_weapon_count: number;
};

export type MatchPlayerRow = Selectable<MatchPlayerTable>;
