//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#if SLOW_PROTOBUF
// Generated from: cstrike15_usermessages.proto
// Note: requires additional types generated from: google/protobuf/descriptor.proto
// Note: requires additional types generated from: netmessages.proto
// Note: requires additional types generated from: cstrike15_gcmessages.proto
namespace DemoInfo.Messages
{
	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VGUIMenu")]
	public partial class CCSUsrMsg_VGUIMenu : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_VGUIMenu() { }


		private string _name = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string name
		{
			get { return _name; }
			set { _name = value; }
		}

		private bool _show = default(bool);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"show", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool show
		{
			get { return _show; }
			set { _show = value; }
		}
		private readonly global::System.Collections.Generic.List<CCSUsrMsg_VGUIMenu.Subkey> _subkeys = new global::System.Collections.Generic.List<CCSUsrMsg_VGUIMenu.Subkey>();
		[global::ProtoBuf.ProtoMember(3, Name = @"subkeys", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<CCSUsrMsg_VGUIMenu.Subkey> subkeys
		{
			get { return _subkeys; }
		}

		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Subkey")]
		public partial class Subkey : global::ProtoBuf.IExtensible
		{
			public Subkey() { }


			private string _name = "";
			[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue("")]
			public string name
			{
				get { return _name; }
				set { _name = value; }
			}

			private string _str = "";
			[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"str", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue("")]
			public string str
			{
				get { return _str; }
				set { _str = value; }
			}
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Geiger")]
	public partial class CCSUsrMsg_Geiger : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_Geiger() { }


		private int _range = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int range
		{
			get { return _range; }
			set { _range = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Train")]
	public partial class CCSUsrMsg_Train : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_Train() { }


		private int _train = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"train", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int train
		{
			get { return _train; }
			set { _train = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_HudText")]
	public partial class CCSUsrMsg_HudText : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_HudText() { }


		private string _text = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string text
		{
			get { return _text; }
			set { _text = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SayText")]
	public partial class CCSUsrMsg_SayText : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_SayText() { }


		private int _ent_idx = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"ent_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int ent_idx
		{
			get { return _ent_idx; }
			set { _ent_idx = value; }
		}

		private string _text = "";
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string text
		{
			get { return _text; }
			set { _text = value; }
		}

		private bool _chat = default(bool);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"chat", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool chat
		{
			get { return _chat; }
			set { _chat = value; }
		}

		private bool _textallchat = default(bool);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"textallchat", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool textallchat
		{
			get { return _textallchat; }
			set { _textallchat = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SayText2")]
	public partial class CCSUsrMsg_SayText2 : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_SayText2() { }


		private int _ent_idx = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"ent_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int ent_idx
		{
			get { return _ent_idx; }
			set { _ent_idx = value; }
		}

		private bool _chat = default(bool);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"chat", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool chat
		{
			get { return _chat; }
			set { _chat = value; }
		}

		private string _msg_name = "";
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"msg_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string msg_name
		{
			get { return _msg_name; }
			set { _msg_name = value; }
		}
		private readonly global::System.Collections.Generic.List<string> _params = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(4, Name = @"params", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> @params
		{
			get { return _params; }
		}


		private bool _textallchat = default(bool);
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"textallchat", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool textallchat
		{
			get { return _textallchat; }
			set { _textallchat = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_TextMsg")]
	public partial class CCSUsrMsg_TextMsg : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_TextMsg() { }


		private int _msg_dst = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"msg_dst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int msg_dst
		{
			get { return _msg_dst; }
			set { _msg_dst = value; }
		}
		private readonly global::System.Collections.Generic.List<string> _params = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(3, Name = @"params", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> @params
		{
			get { return _params; }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_HudMsg")]
	public partial class CCSUsrMsg_HudMsg : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_HudMsg() { }


		private int _channel = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int channel
		{
			get { return _channel; }
			set { _channel = value; }
		}

		private CMsgVector2D _pos = null;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public CMsgVector2D pos
		{
			get { return _pos; }
			set { _pos = value; }
		}

		private CMsgRGBA _clr1 = null;
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"clr1", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public CMsgRGBA clr1
		{
			get { return _clr1; }
			set { _clr1 = value; }
		}

		private CMsgRGBA _clr2 = null;
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"clr2", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public CMsgRGBA clr2
		{
			get { return _clr2; }
			set { _clr2 = value; }
		}

		private int _effect = default(int);
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int effect
		{
			get { return _effect; }
			set { _effect = value; }
		}

		private float _fade_in_time = default(float);
		[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"fade_in_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float fade_in_time
		{
			get { return _fade_in_time; }
			set { _fade_in_time = value; }
		}

		private float _fade_out_time = default(float);
		[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"fade_out_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float fade_out_time
		{
			get { return _fade_out_time; }
			set { _fade_out_time = value; }
		}

		private float _hold_time = default(float);
		[global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"hold_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float hold_time
		{
			get { return _hold_time; }
			set { _hold_time = value; }
		}

		private float _fx_time = default(float);
		[global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"fx_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float fx_time
		{
			get { return _fx_time; }
			set { _fx_time = value; }
		}

		private string _text = "";
		[global::ProtoBuf.ProtoMember(11, IsRequired = false, Name = @"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string text
		{
			get { return _text; }
			set { _text = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Shake")]
	public partial class CCSUsrMsg_Shake : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_Shake() { }


		private int _command = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int command
		{
			get { return _command; }
			set { _command = value; }
		}

		private float _local_amplitude = default(float);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"local_amplitude", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float local_amplitude
		{
			get { return _local_amplitude; }
			set { _local_amplitude = value; }
		}

		private float _frequency = default(float);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"frequency", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float frequency
		{
			get { return _frequency; }
			set { _frequency = value; }
		}

		private float _duration = default(float);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float duration
		{
			get { return _duration; }
			set { _duration = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Fade")]
	public partial class CCSUsrMsg_Fade : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_Fade() { }


		private int _duration = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int duration
		{
			get { return _duration; }
			set { _duration = value; }
		}

		private int _hold_time = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"hold_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int hold_time
		{
			get { return _hold_time; }
			set { _hold_time = value; }
		}

		private int _flags = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int flags
		{
			get { return _flags; }
			set { _flags = value; }
		}

		private CMsgRGBA _clr = null;
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"clr", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public CMsgRGBA clr
		{
			get { return _clr; }
			set { _clr = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Rumble")]
	public partial class CCSUsrMsg_Rumble : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_Rumble() { }


		private int _index = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int index
		{
			get { return _index; }
			set { _index = value; }
		}

		private int _data = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int data
		{
			get { return _data; }
			set { _data = value; }
		}

		private int _flags = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int flags
		{
			get { return _flags; }
			set { _flags = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_CloseCaption")]
	public partial class CCSUsrMsg_CloseCaption : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_CloseCaption() { }


		private uint _hash = default(uint);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"hash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(uint))]
		public uint hash
		{
			get { return _hash; }
			set { _hash = value; }
		}

		private int _duration = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int duration
		{
			get { return _duration; }
			set { _duration = value; }
		}

		private bool _from_player = default(bool);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"from_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool from_player
		{
			get { return _from_player; }
			set { _from_player = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_CloseCaptionDirect")]
	public partial class CCSUsrMsg_CloseCaptionDirect : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_CloseCaptionDirect() { }


		private uint _hash = default(uint);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"hash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(uint))]
		public uint hash
		{
			get { return _hash; }
			set { _hash = value; }
		}

		private int _duration = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int duration
		{
			get { return _duration; }
			set { _duration = value; }
		}

		private bool _from_player = default(bool);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"from_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool from_player
		{
			get { return _from_player; }
			set { _from_player = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SendAudio")]
	public partial class CCSUsrMsg_SendAudio : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_SendAudio() { }


		private string _radio_sound = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"radio_sound", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string radio_sound
		{
			get { return _radio_sound; }
			set { _radio_sound = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_RawAudio")]
	public partial class CCSUsrMsg_RawAudio : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_RawAudio() { }


		private int _pitch = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"pitch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int pitch
		{
			get { return _pitch; }
			set { _pitch = value; }
		}

		private int _entidx = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"entidx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int entidx
		{
			get { return _entidx; }
			set { _entidx = value; }
		}

		private float _duration = default(float);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float duration
		{
			get { return _duration; }
			set { _duration = value; }
		}

		private string _voice_filename = "";
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"voice_filename", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string voice_filename
		{
			get { return _voice_filename; }
			set { _voice_filename = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VoiceMask")]
	public partial class CCSUsrMsg_VoiceMask : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_VoiceMask() { }

		private readonly global::System.Collections.Generic.List<CCSUsrMsg_VoiceMask.PlayerMask> _player_masks = new global::System.Collections.Generic.List<CCSUsrMsg_VoiceMask.PlayerMask>();
		[global::ProtoBuf.ProtoMember(1, Name = @"player_masks", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<CCSUsrMsg_VoiceMask.PlayerMask> player_masks
		{
			get { return _player_masks; }
		}


		private bool _player_mod_enable = default(bool);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"player_mod_enable", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool player_mod_enable
		{
			get { return _player_mod_enable; }
			set { _player_mod_enable = value; }
		}
		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PlayerMask")]
		public partial class PlayerMask : global::ProtoBuf.IExtensible
		{
			public PlayerMask() { }


			private int _game_rules_mask = default(int);
			[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"game_rules_mask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int game_rules_mask
			{
				get { return _game_rules_mask; }
				set { _game_rules_mask = value; }
			}

			private int _ban_masks = default(int);
			[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"ban_masks", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int ban_masks
			{
				get { return _ban_masks; }
				set { _ban_masks = value; }
			}
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_Damage")]
	public partial class CCSUsrMsg_Damage : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_Damage() { }


		private int _amount = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int amount
		{
			get { return _amount; }
			set { _amount = value; }
		}

		private CMsgVector _inflictor_world_pos = null;
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"inflictor_world_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public CMsgVector inflictor_world_pos
		{
			get { return _inflictor_world_pos; }
			set { _inflictor_world_pos = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_RadioText")]
	public partial class CCSUsrMsg_RadioText : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_RadioText() { }


		private int _msg_dst = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"msg_dst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int msg_dst
		{
			get { return _msg_dst; }
			set { _msg_dst = value; }
		}

		private int _client = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"client", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int client
		{
			get { return _client; }
			set { _client = value; }
		}

		private string _msg_name = "";
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"msg_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string msg_name
		{
			get { return _msg_name; }
			set { _msg_name = value; }
		}
		private readonly global::System.Collections.Generic.List<string> _params = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(4, Name = @"params", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> @params
		{
			get { return _params; }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_HintText")]
	public partial class CCSUsrMsg_HintText : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_HintText() { }


		private string _text = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string text
		{
			get { return _text; }
			set { _text = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_KeyHintText")]
	public partial class CCSUsrMsg_KeyHintText : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_KeyHintText() { }

		private readonly global::System.Collections.Generic.List<string> _hints = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(1, Name = @"hints", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> hints
		{
			get { return _hints; }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ProcessSpottedEntityUpdate")]
	public partial class CCSUsrMsg_ProcessSpottedEntityUpdate : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ProcessSpottedEntityUpdate() { }


		private bool _new_update = default(bool);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"new_update", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool new_update
		{
			get { return _new_update; }
			set { _new_update = value; }
		}
		private readonly global::System.Collections.Generic.List<CCSUsrMsg_ProcessSpottedEntityUpdate.SpottedEntityUpdate> _entity_updates = new global::System.Collections.Generic.List<CCSUsrMsg_ProcessSpottedEntityUpdate.SpottedEntityUpdate>();
		[global::ProtoBuf.ProtoMember(2, Name = @"entity_updates", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<CCSUsrMsg_ProcessSpottedEntityUpdate.SpottedEntityUpdate> entity_updates
		{
			get { return _entity_updates; }
		}

		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SpottedEntityUpdate")]
		public partial class SpottedEntityUpdate : global::ProtoBuf.IExtensible
		{
			public SpottedEntityUpdate() { }


			private int _entity_idx = default(int);
			[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"entity_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int entity_idx
			{
				get { return _entity_idx; }
				set { _entity_idx = value; }
			}

			private int _class_id = default(int);
			[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"class_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int class_id
			{
				get { return _class_id; }
				set { _class_id = value; }
			}

			private int _origin_x = default(int);
			[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"origin_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int origin_x
			{
				get { return _origin_x; }
				set { _origin_x = value; }
			}

			private int _origin_y = default(int);
			[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"origin_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int origin_y
			{
				get { return _origin_y; }
				set { _origin_y = value; }
			}

			private int _origin_z = default(int);
			[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"origin_z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int origin_z
			{
				get { return _origin_z; }
				set { _origin_z = value; }
			}

			private int _angle_y = default(int);
			[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"angle_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int angle_y
			{
				get { return _angle_y; }
				set { _angle_y = value; }
			}

			private bool _defuser = default(bool);
			[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"defuser", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue(default(bool))]
			public bool defuser
			{
				get { return _defuser; }
				set { _defuser = value; }
			}

			private bool _player_has_defuser = default(bool);
			[global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"player_has_defuser", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue(default(bool))]
			public bool player_has_defuser
			{
				get { return _player_has_defuser; }
				set { _player_has_defuser = value; }
			}

			private bool _player_has_c4 = default(bool);
			[global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"player_has_c4", DataFormat = global::ProtoBuf.DataFormat.Default)]
			[global::System.ComponentModel.DefaultValue(default(bool))]
			public bool player_has_c4
			{
				get { return _player_has_c4; }
				set { _player_has_c4 = value; }
			}
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SendPlayerItemDrops")]
	public partial class CCSUsrMsg_SendPlayerItemDrops : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_SendPlayerItemDrops() { }

		private readonly global::System.Collections.Generic.List<CEconItemPreviewDataBlock> _entity_updates = new global::System.Collections.Generic.List<CEconItemPreviewDataBlock>();
		[global::ProtoBuf.ProtoMember(1, Name = @"entity_updates", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<CEconItemPreviewDataBlock> entity_updates
		{
			get { return _entity_updates; }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SendPlayerItemFound")]
	public partial class CCSUsrMsg_SendPlayerItemFound : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_SendPlayerItemFound() { }


		private CEconItemPreviewDataBlock _iteminfo = null;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"iteminfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public CEconItemPreviewDataBlock iteminfo
		{
			get { return _iteminfo; }
			set { _iteminfo = value; }
		}

		private int _entindex = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"entindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int entindex
		{
			get { return _entindex; }
			set { _entindex = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ReloadEffect")]
	public partial class CCSUsrMsg_ReloadEffect : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ReloadEffect() { }


		private int _entidx = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"entidx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int entidx
		{
			get { return _entidx; }
			set { _entidx = value; }
		}

		private int _actanim = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"actanim", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int actanim
		{
			get { return _actanim; }
			set { _actanim = value; }
		}

		private float _origin_x = default(float);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"origin_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float origin_x
		{
			get { return _origin_x; }
			set { _origin_x = value; }
		}

		private float _origin_y = default(float);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"origin_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float origin_y
		{
			get { return _origin_y; }
			set { _origin_y = value; }
		}

		private float _origin_z = default(float);
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"origin_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float origin_z
		{
			get { return _origin_z; }
			set { _origin_z = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_AdjustMoney")]
	public partial class CCSUsrMsg_AdjustMoney : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_AdjustMoney() { }


		private int _amount = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int amount
		{
			get { return _amount; }
			set { _amount = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ReportHit")]
	public partial class CCSUsrMsg_ReportHit : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ReportHit() { }


		private float _pos_x = default(float);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float pos_x
		{
			get { return _pos_x; }
			set { _pos_x = value; }
		}

		private float _pos_y = default(float);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float pos_y
		{
			get { return _pos_y; }
			set { _pos_y = value; }
		}

		private float _timestamp = default(float);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float timestamp
		{
			get { return _timestamp; }
			set { _timestamp = value; }
		}

		private float _pos_z = default(float);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float pos_z
		{
			get { return _pos_z; }
			set { _pos_z = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_KillCam")]
	public partial class CCSUsrMsg_KillCam : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_KillCam() { }


		private int _obs_mode = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"obs_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int obs_mode
		{
			get { return _obs_mode; }
			set { _obs_mode = value; }
		}

		private int _first_target = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"first_target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int first_target
		{
			get { return _first_target; }
			set { _first_target = value; }
		}

		private int _second_target = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"second_target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int second_target
		{
			get { return _second_target; }
			set { _second_target = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_DesiredTimescale")]
	public partial class CCSUsrMsg_DesiredTimescale : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_DesiredTimescale() { }


		private float _desired_timescale = default(float);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"desired_timescale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float desired_timescale
		{
			get { return _desired_timescale; }
			set { _desired_timescale = value; }
		}

		private float _duration_realtime_sec = default(float);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"duration_realtime_sec", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float duration_realtime_sec
		{
			get { return _duration_realtime_sec; }
			set { _duration_realtime_sec = value; }
		}

		private int _interpolator_type = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"interpolator_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int interpolator_type
		{
			get { return _interpolator_type; }
			set { _interpolator_type = value; }
		}

		private float _start_blend_time = default(float);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"start_blend_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float start_blend_time
		{
			get { return _start_blend_time; }
			set { _start_blend_time = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_CurrentTimescale")]
	public partial class CCSUsrMsg_CurrentTimescale : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_CurrentTimescale() { }


		private float _cur_timescale = default(float);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"cur_timescale", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
		[global::System.ComponentModel.DefaultValue(default(float))]
		public float cur_timescale
		{
			get { return _cur_timescale; }
			set { _cur_timescale = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_AchievementEvent")]
	public partial class CCSUsrMsg_AchievementEvent : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_AchievementEvent() { }


		private int _achievement = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"achievement", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int achievement
		{
			get { return _achievement; }
			set { _achievement = value; }
		}

		private int _count = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int count
		{
			get { return _count; }
			set { _count = value; }
		}

		private int _user_id = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int user_id
		{
			get { return _user_id; }
			set { _user_id = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_MatchEndConditions")]
	public partial class CCSUsrMsg_MatchEndConditions : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_MatchEndConditions() { }


		private int _fraglimit = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"fraglimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int fraglimit
		{
			get { return _fraglimit; }
			set { _fraglimit = value; }
		}

		private int _mp_maxrounds = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"mp_maxrounds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int mp_maxrounds
		{
			get { return _mp_maxrounds; }
			set { _mp_maxrounds = value; }
		}

		private int _mp_winlimit = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"mp_winlimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int mp_winlimit
		{
			get { return _mp_winlimit; }
			set { _mp_winlimit = value; }
		}

		private int _mp_timelimit = default(int);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"mp_timelimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int mp_timelimit
		{
			get { return _mp_timelimit; }
			set { _mp_timelimit = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_PlayerStatsUpdate")]
	public partial class CCSUsrMsg_PlayerStatsUpdate : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_PlayerStatsUpdate() { }


		private int _version = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int version
		{
			get { return _version; }
			set { _version = value; }
		}
		private readonly global::System.Collections.Generic.List<CCSUsrMsg_PlayerStatsUpdate.Stat> _stats = new global::System.Collections.Generic.List<CCSUsrMsg_PlayerStatsUpdate.Stat>();
		[global::ProtoBuf.ProtoMember(4, Name = @"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<CCSUsrMsg_PlayerStatsUpdate.Stat> stats
		{
			get { return _stats; }
		}


		private int _user_id = default(int);
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int user_id
		{
			get { return _user_id; }
			set { _user_id = value; }
		}

		private int _crc = default(int);
		[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"crc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int crc
		{
			get { return _crc; }
			set { _crc = value; }
		}
		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Stat")]
		public partial class Stat : global::ProtoBuf.IExtensible
		{
			public Stat() { }


			private int _idx = default(int);
			[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int idx
			{
				get { return _idx; }
				set { _idx = value; }
			}

			private int _delta = default(int);
			[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"delta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int delta
			{
				get { return _delta; }
				set { _delta = value; }
			}
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_DisplayInventory")]
	public partial class CCSUsrMsg_DisplayInventory : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_DisplayInventory() { }


		private bool _display = default(bool);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"display", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool display
		{
			get { return _display; }
			set { _display = value; }
		}

		private int _user_id = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int user_id
		{
			get { return _user_id; }
			set { _user_id = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_QuestProgress")]
	public partial class CCSUsrMsg_QuestProgress : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_QuestProgress() { }


		private uint _quest_id = default(uint);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"quest_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(uint))]
		public uint quest_id
		{
			get { return _quest_id; }
			set { _quest_id = value; }
		}

		private uint _normal_points = default(uint);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"normal_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(uint))]
		public uint normal_points
		{
			get { return _normal_points; }
			set { _normal_points = value; }
		}

		private uint _bonus_points = default(uint);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"bonus_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(uint))]
		public uint bonus_points
		{
			get { return _bonus_points; }
			set { _bonus_points = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_XRankGet")]
	public partial class CCSUsrMsg_XRankGet : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_XRankGet() { }


		private int _mode_idx = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"mode_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int mode_idx
		{
			get { return _mode_idx; }
			set { _mode_idx = value; }
		}

		private int _controller = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"controller", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int controller
		{
			get { return _controller; }
			set { _controller = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_XRankUpd")]
	public partial class CCSUsrMsg_XRankUpd : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_XRankUpd() { }


		private int _mode_idx = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"mode_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int mode_idx
		{
			get { return _mode_idx; }
			set { _mode_idx = value; }
		}

		private int _controller = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"controller", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int controller
		{
			get { return _controller; }
			set { _controller = value; }
		}

		private int _ranking = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int ranking
		{
			get { return _ranking; }
			set { _ranking = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_CallVoteFailed")]
	public partial class CCSUsrMsg_CallVoteFailed : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_CallVoteFailed() { }


		private int _reason = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int reason
		{
			get { return _reason; }
			set { _reason = value; }
		}

		private int _time = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int time
		{
			get { return _time; }
			set { _time = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VoteStart")]
	public partial class CCSUsrMsg_VoteStart : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_VoteStart() { }


		private int _team = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int team
		{
			get { return _team; }
			set { _team = value; }
		}

		private int _ent_idx = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"ent_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int ent_idx
		{
			get { return _ent_idx; }
			set { _ent_idx = value; }
		}

		private int _vote_type = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"vote_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int vote_type
		{
			get { return _vote_type; }
			set { _vote_type = value; }
		}

		private string _disp_str = "";
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"disp_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string disp_str
		{
			get { return _disp_str; }
			set { _disp_str = value; }
		}

		private string _details_str = "";
		[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"details_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string details_str
		{
			get { return _details_str; }
			set { _details_str = value; }
		}

		private string _other_team_str = "";
		[global::ProtoBuf.ProtoMember(6, IsRequired = false, Name = @"other_team_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string other_team_str
		{
			get { return _other_team_str; }
			set { _other_team_str = value; }
		}

		private bool _is_yes_no_vote = default(bool);
		[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name = @"is_yes_no_vote", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool is_yes_no_vote
		{
			get { return _is_yes_no_vote; }
			set { _is_yes_no_vote = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VotePass")]
	public partial class CCSUsrMsg_VotePass : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_VotePass() { }


		private int _team = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int team
		{
			get { return _team; }
			set { _team = value; }
		}

		private int _vote_type = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"vote_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int vote_type
		{
			get { return _vote_type; }
			set { _vote_type = value; }
		}

		private string _disp_str = "";
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"disp_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string disp_str
		{
			get { return _disp_str; }
			set { _disp_str = value; }
		}

		private string _details_str = "";
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"details_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string details_str
		{
			get { return _details_str; }
			set { _details_str = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VoteFailed")]
	public partial class CCSUsrMsg_VoteFailed : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_VoteFailed() { }


		private int _team = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int team
		{
			get { return _team; }
			set { _team = value; }
		}

		private int _reason = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int reason
		{
			get { return _reason; }
			set { _reason = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_VoteSetup")]
	public partial class CCSUsrMsg_VoteSetup : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_VoteSetup() { }

		private readonly global::System.Collections.Generic.List<string> _potential_issues = new global::System.Collections.Generic.List<string>();
		[global::ProtoBuf.ProtoMember(1, Name = @"potential_issues", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<string> potential_issues
		{
			get { return _potential_issues; }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_SendLastKillerDamageToClient")]
	public partial class CCSUsrMsg_SendLastKillerDamageToClient : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_SendLastKillerDamageToClient() { }


		private int _num_hits_given = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"num_hits_given", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int num_hits_given
		{
			get { return _num_hits_given; }
			set { _num_hits_given = value; }
		}

		private int _damage_given = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"damage_given", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int damage_given
		{
			get { return _damage_given; }
			set { _damage_given = value; }
		}

		private int _num_hits_taken = default(int);
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"num_hits_taken", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int num_hits_taken
		{
			get { return _num_hits_taken; }
			set { _num_hits_taken = value; }
		}

		private int _damage_taken = default(int);
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"damage_taken", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int damage_taken
		{
			get { return _damage_taken; }
			set { _damage_taken = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ServerRankUpdate")]
	public partial class CCSUsrMsg_ServerRankUpdate : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ServerRankUpdate() { }

		private readonly global::System.Collections.Generic.List<CCSUsrMsg_ServerRankUpdate.RankUpdate> _rank_update = new global::System.Collections.Generic.List<CCSUsrMsg_ServerRankUpdate.RankUpdate>();
		[global::ProtoBuf.ProtoMember(1, Name = @"rank_update", DataFormat = global::ProtoBuf.DataFormat.Default)]
		public global::System.Collections.Generic.List<CCSUsrMsg_ServerRankUpdate.RankUpdate> rank_update
		{
			get { return _rank_update; }
		}

		[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"RankUpdate")]
		public partial class RankUpdate : global::ProtoBuf.IExtensible
		{
			public RankUpdate() { }


			private int _account_id = default(int);
			[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int account_id
			{
				get { return _account_id; }
				set { _account_id = value; }
			}

			private int _rank_old = default(int);
			[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"rank_old", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int rank_old
			{
				get { return _rank_old; }
				set { _rank_old = value; }
			}

			private int _rank_new = default(int);
			[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"rank_new", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int rank_new
			{
				get { return _rank_new; }
				set { _rank_new = value; }
			}

			private int _num_wins = default(int);
			[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"num_wins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
			[global::System.ComponentModel.DefaultValue(default(int))]
			public int num_wins
			{
				get { return _num_wins; }
				set { _num_wins = value; }
			}

			private float _rank_change = default(float);
			[global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"rank_change", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
			[global::System.ComponentModel.DefaultValue(default(float))]
			public float rank_change
			{
				get { return _rank_change; }
				set { _rank_change = value; }
			}
			private global::ProtoBuf.IExtension extensionObject;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
		}

		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_XpUpdate")]
	public partial class CCSUsrMsg_XpUpdate : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_XpUpdate() { }


		private CMsgGCCstrike15_v2_GC2ServerNotifyXPRewarded _data = null;
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(null)]
		public CMsgGCCstrike15_v2_GC2ServerNotifyXPRewarded data
		{
			get { return _data; }
			set { _data = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ItemPickup")]
	public partial class CCSUsrMsg_ItemPickup : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ItemPickup() { }


		private string _item = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string item
		{
			get { return _item; }
			set { _item = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ShowMenu")]
	public partial class CCSUsrMsg_ShowMenu : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ShowMenu() { }


		private int _bits_valid_slots = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"bits_valid_slots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int bits_valid_slots
		{
			get { return _bits_valid_slots; }
			set { _bits_valid_slots = value; }
		}

		private int _display_time = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"display_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int display_time
		{
			get { return _display_time; }
			set { _display_time = value; }
		}

		private string _menu_string = "";
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"menu_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string menu_string
		{
			get { return _menu_string; }
			set { _menu_string = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_BarTime")]
	public partial class CCSUsrMsg_BarTime : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_BarTime() { }


		private string _time = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string time
		{
			get { return _time; }
			set { _time = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_AmmoDenied")]
	public partial class CCSUsrMsg_AmmoDenied : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_AmmoDenied() { }


		private int _ammoIdx = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"ammoIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int ammoIdx
		{
			get { return _ammoIdx; }
			set { _ammoIdx = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_MarkAchievement")]
	public partial class CCSUsrMsg_MarkAchievement : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_MarkAchievement() { }


		private string _achievement = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"achievement", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string achievement
		{
			get { return _achievement; }
			set { _achievement = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_MatchStatsUpdate")]
	public partial class CCSUsrMsg_MatchStatsUpdate : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_MatchStatsUpdate() { }


		private string _update = "";
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"update", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string update
		{
			get { return _update; }
			set { _update = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ItemDrop")]
	public partial class CCSUsrMsg_ItemDrop : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ItemDrop() { }


		private long _itemid = default(long);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(long))]
		public long itemid
		{
			get { return _itemid; }
			set { _itemid = value; }
		}

		private bool _death = default(bool);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"death", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool death
		{
			get { return _death; }
			set { _death = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_GlowPropTurnOff")]
	public partial class CCSUsrMsg_GlowPropTurnOff : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_GlowPropTurnOff() { }


		private int _entidx = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"entidx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int entidx
		{
			get { return _entidx; }
			set { _entidx = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_RoundBackupFilenames")]
	public partial class CCSUsrMsg_RoundBackupFilenames : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_RoundBackupFilenames() { }


		private int _count = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int count
		{
			get { return _count; }
			set { _count = value; }
		}

		private int _index = default(int);
		[global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int index
		{
			get { return _index; }
			set { _index = value; }
		}

		private string _filename = "";
		[global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"filename", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string filename
		{
			get { return _filename; }
			set { _filename = value; }
		}

		private string _nicename = "";
		[global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"nicename", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue("")]
		public string nicename
		{
			get { return _nicename; }
			set { _nicename = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ResetHud")]
	public partial class CCSUsrMsg_ResetHud : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ResetHud() { }


		private bool _reset = default(bool);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"reset", DataFormat = global::ProtoBuf.DataFormat.Default)]
		[global::System.ComponentModel.DefaultValue(default(bool))]
		public bool reset
		{
			get { return _reset; }
			set { _reset = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_GameTitle")]
	public partial class CCSUsrMsg_GameTitle : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_GameTitle() { }


		private int _dummy = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"dummy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int dummy
		{
			get { return _dummy; }
			set { _dummy = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_RequestState")]
	public partial class CCSUsrMsg_RequestState : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_RequestState() { }


		private int _dummy = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"dummy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int dummy
		{
			get { return _dummy; }
			set { _dummy = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_StopSpectatorMode")]
	public partial class CCSUsrMsg_StopSpectatorMode : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_StopSpectatorMode() { }


		private int _dummy = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"dummy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int dummy
		{
			get { return _dummy; }
			set { _dummy = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_DisconnectToLobby")]
	public partial class CCSUsrMsg_DisconnectToLobby : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_DisconnectToLobby() { }


		private int _dummy = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"dummy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int dummy
		{
			get { return _dummy; }
			set { _dummy = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_WarmupHasEnded")]
	public partial class CCSUsrMsg_WarmupHasEnded : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_WarmupHasEnded() { }


		private int _dummy = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"dummy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int dummy
		{
			get { return _dummy; }
			set { _dummy = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ClientInfo")]
	public partial class CCSUsrMsg_ClientInfo : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ClientInfo() { }


		private int _dummy = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"dummy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int dummy
		{
			get { return _dummy; }
			set { _dummy = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CCSUsrMsg_ServerRankRevealAll")]
	public partial class CCSUsrMsg_ServerRankRevealAll : global::ProtoBuf.IExtensible
	{
		public CCSUsrMsg_ServerRankRevealAll() { }


		private int _seconds_till_shutdown = default(int);
		[global::ProtoBuf.ProtoMember(1, IsRequired = false, Name = @"seconds_till_shutdown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
		[global::System.ComponentModel.DefaultValue(default(int))]
		public int seconds_till_shutdown
		{
			get { return _seconds_till_shutdown; }
			set { _seconds_till_shutdown = value; }
		}
		private global::ProtoBuf.IExtension extensionObject;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
		{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
	}

	[global::ProtoBuf.ProtoContract(Name = @"ECstrike15UserMessages", EnumPassthru = true)]
	public enum ECstrike15UserMessages
	{

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VGUIMenu", Value = 1)]
		CS_UM_VGUIMenu = 1,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Geiger", Value = 2)]
		CS_UM_Geiger = 2,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Train", Value = 3)]
		CS_UM_Train = 3,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_HudText", Value = 4)]
		CS_UM_HudText = 4,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SayText", Value = 5)]
		CS_UM_SayText = 5,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SayText2", Value = 6)]
		CS_UM_SayText2 = 6,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_TextMsg", Value = 7)]
		CS_UM_TextMsg = 7,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_HudMsg", Value = 8)]
		CS_UM_HudMsg = 8,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ResetHud", Value = 9)]
		CS_UM_ResetHud = 9,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_GameTitle", Value = 10)]
		CS_UM_GameTitle = 10,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Shake", Value = 12)]
		CS_UM_Shake = 12,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Fade", Value = 13)]
		CS_UM_Fade = 13,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Rumble", Value = 14)]
		CS_UM_Rumble = 14,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_CloseCaption", Value = 15)]
		CS_UM_CloseCaption = 15,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_CloseCaptionDirect", Value = 16)]
		CS_UM_CloseCaptionDirect = 16,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SendAudio", Value = 17)]
		CS_UM_SendAudio = 17,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_RawAudio", Value = 18)]
		CS_UM_RawAudio = 18,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VoiceMask", Value = 19)]
		CS_UM_VoiceMask = 19,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_RequestState", Value = 20)]
		CS_UM_RequestState = 20,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_Damage", Value = 21)]
		CS_UM_Damage = 21,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_RadioText", Value = 22)]
		CS_UM_RadioText = 22,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_HintText", Value = 23)]
		CS_UM_HintText = 23,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_KeyHintText", Value = 24)]
		CS_UM_KeyHintText = 24,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ProcessSpottedEntityUpdate", Value = 25)]
		CS_UM_ProcessSpottedEntityUpdate = 25,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ReloadEffect", Value = 26)]
		CS_UM_ReloadEffect = 26,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_AdjustMoney", Value = 27)]
		CS_UM_AdjustMoney = 27,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_UpdateTeamMoney", Value = 28)]
		CS_UM_UpdateTeamMoney = 28,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_StopSpectatorMode", Value = 29)]
		CS_UM_StopSpectatorMode = 29,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_KillCam", Value = 30)]
		CS_UM_KillCam = 30,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_DesiredTimescale", Value = 31)]
		CS_UM_DesiredTimescale = 31,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_CurrentTimescale", Value = 32)]
		CS_UM_CurrentTimescale = 32,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_AchievementEvent", Value = 33)]
		CS_UM_AchievementEvent = 33,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_MatchEndConditions", Value = 34)]
		CS_UM_MatchEndConditions = 34,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_DisconnectToLobby", Value = 35)]
		CS_UM_DisconnectToLobby = 35,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_PlayerStatsUpdate", Value = 36)]
		CS_UM_PlayerStatsUpdate = 36,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_DisplayInventory", Value = 37)]
		CS_UM_DisplayInventory = 37,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_WarmupHasEnded", Value = 38)]
		CS_UM_WarmupHasEnded = 38,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ClientInfo", Value = 39)]
		CS_UM_ClientInfo = 39,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_XRankGet", Value = 40)]
		CS_UM_XRankGet = 40,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_XRankUpd", Value = 41)]
		CS_UM_XRankUpd = 41,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_CallVoteFailed", Value = 45)]
		CS_UM_CallVoteFailed = 45,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VoteStart", Value = 46)]
		CS_UM_VoteStart = 46,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VotePass", Value = 47)]
		CS_UM_VotePass = 47,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VoteFailed", Value = 48)]
		CS_UM_VoteFailed = 48,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_VoteSetup", Value = 49)]
		CS_UM_VoteSetup = 49,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ServerRankRevealAll", Value = 50)]
		CS_UM_ServerRankRevealAll = 50,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SendLastKillerDamageToClient", Value = 51)]
		CS_UM_SendLastKillerDamageToClient = 51,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ServerRankUpdate", Value = 52)]
		CS_UM_ServerRankUpdate = 52,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ItemPickup", Value = 53)]
		CS_UM_ItemPickup = 53,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ShowMenu", Value = 54)]
		CS_UM_ShowMenu = 54,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_BarTime", Value = 55)]
		CS_UM_BarTime = 55,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_AmmoDenied", Value = 56)]
		CS_UM_AmmoDenied = 56,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_MarkAchievement", Value = 57)]
		CS_UM_MarkAchievement = 57,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_MatchStatsUpdate", Value = 58)]
		CS_UM_MatchStatsUpdate = 58,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ItemDrop", Value = 59)]
		CS_UM_ItemDrop = 59,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_GlowPropTurnOff", Value = 60)]
		CS_UM_GlowPropTurnOff = 60,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SendPlayerItemDrops", Value = 61)]
		CS_UM_SendPlayerItemDrops = 61,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_RoundBackupFilenames", Value = 62)]
		CS_UM_RoundBackupFilenames = 62,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_SendPlayerItemFound", Value = 63)]
		CS_UM_SendPlayerItemFound = 63,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_ReportHit", Value = 64)]
		CS_UM_ReportHit = 64,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_XpUpdate", Value = 65)]
		CS_UM_XpUpdate = 65,

		[global::ProtoBuf.ProtoEnum(Name = @"CS_UM_QuestProgress", Value = 66)]
		CS_UM_QuestProgress = 66
	}

}
#endif
