//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb.
        /// </summary>
        public static string Bomb {
            get {
                return ResourceManager.GetString("Bomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap colors {
            get {
                object obj = ResourceManager.GetObject("colors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoy.
        /// </summary>
        public static string Decoy {
            get {
                return ResourceManager.GetString("Decoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} defused the bomb on bomb site {1}.
        /// </summary>
        public static string DefusedTheBombOnBombSite {
            get {
                return ResourceManager.GetString("DefusedTheBombOnBombSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashbang.
        /// </summary>
        public static string Flashbang {
            get {
                return ResourceManager.GetString("Flashbang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE.
        /// </summary>
        public static string HE {
            get {
                return ResourceManager.GetString("HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} killed {1}.
        /// </summary>
        public static string Killed {
            get {
                return ResourceManager.GetString("Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        public static string Kills {
            get {
                return ResourceManager.GetString("Kills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molotov.
        /// </summary>
        public static string Molotov {
            get {
                return ResourceManager.GetString("Molotov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} planted the bomb on bomb site {1}.
        /// </summary>
        public static string PlantedTheBombOnBombSite {
            get {
                return ResourceManager.GetString("PlantedTheBombOnBombSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke.
        /// </summary>
        public static string Smoke {
            get {
                return ResourceManager.GetString("Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR STEAM API GOES HERE.
        /// </summary>
        public static string steam_api_key {
            get {
                return ResourceManager.GetString("steam_api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bomb exploded on bomb site {0}.
        /// </summary>
        public static string TheBombExplodedOnBombSite {
            get {
                return ResourceManager.GetString("TheBombExplodedOnBombSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thrown a decoy.
        /// </summary>
        public static string ThrownDecoy {
            get {
                return ResourceManager.GetString("ThrownDecoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thrown a flashbang.
        /// </summary>
        public static string ThrownFlashbang {
            get {
                return ResourceManager.GetString("ThrownFlashbang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thrown a HE grenade.
        /// </summary>
        public static string ThrownHeGrenade {
            get {
                return ResourceManager.GetString("ThrownHeGrenade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thrown an incendiary.
        /// </summary>
        public static string ThrownIncendiary {
            get {
                return ResourceManager.GetString("ThrownIncendiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thrown a molotov.
        /// </summary>
        public static string ThrownMolotov {
            get {
                return ResourceManager.GetString("ThrownMolotov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thrown a smoke.
        /// </summary>
        public static string ThrownSmoke {
            get {
                return ResourceManager.GetString("ThrownSmoke", resourceCulture);
            }
        }
    }
}
