import {
  DEFAULT_AUDIO_CODEC,
  DEFAULT_DEATH_NOTICES_DURATION,
  DEFAULT_ENCODER_SOFTWARE,
  DEFAULT_FFMPEG_AUDIO_BITRATE,
  DEFAULT_FFMPEG_CONSTANT_RATE_FACTOR,
  DEFAULT_FRAMERATE,
  DEFAULT_HEIGHT_RESOLUTION,
  DEFAULT_VIDEO_CODEC,
  DEFAULT_WIDTH_RESOLUTION,
} from 'csdm/ui/settings/video/default-values';
import { CURRENT_SCHEMA_VERSION } from './schema-version';
import type { Settings } from './settings';
import { Page } from 'csdm/node/settings/page';
import { RankingFilter } from 'csdm/common/types/ranking-filter';
import { AnalysisStatusFilter } from 'csdm/common/types/analysis-status-filter';

export const defaultSettings: Settings = {
  schemaVersion: CURRENT_SCHEMA_VERSION,
  autoDownloadUpdates: true,
  database: {
    hostname: '127.0.0.1',
    port: 5432,
    username: 'postgres',
    password: 'password',
    database: 'csdm',
  },
  folders: [],
  demos: {
    showAllFolders: false,
    currentFolderPath: '',
    sources: [],
    tagIds: [],
    types: [],
    games: [],
    startDate: undefined,
    endDate: undefined,
    analysisStatus: AnalysisStatusFilter.All,
  },
  pinnedPlayerSteamId: '',
  steamApiKey: '',
  faceitApiKey: '',
  ui: {
    locale: 'en',
    theme: 'dark',
    initialPage: Page.Matches,
  },
  analyze: {
    analyzePositions: false,
  },
  playback: {
    width: 1024,
    height: 768,
    fullscreen: false,
    useCustomHighlights: true,
    useCustomLowlights: true,
    highlights: {
      beforeKillDelayInSeconds: 5,
      afterKillDelayInSeconds: 2,
    },
    lowlights: {
      beforeKillDelayInSeconds: 5,
      afterKillDelayInSeconds: 2,
    },
    launchParameters: '',
  },
  video: {
    closeGameAfterRecording: true,
    concatenateSequences: false,
    deleteRawFilesAfterEncoding: true,
    showOnlyDeathNotices: true,
    deathNoticesDuration: DEFAULT_DEATH_NOTICES_DURATION,
    encoderSoftware: DEFAULT_ENCODER_SOFTWARE,
    ffmpegSettings: {
      audioBitrate: DEFAULT_FFMPEG_AUDIO_BITRATE,
      constantRateFactor: DEFAULT_FFMPEG_CONSTANT_RATE_FACTOR,
      customLocationEnabled: false,
      customExecutableLocation: '',
      videoCodec: DEFAULT_VIDEO_CODEC,
      audioCodec: DEFAULT_AUDIO_CODEC,
      inputParameters: '',
      outputParameters: '',
    },
    framerate: DEFAULT_FRAMERATE,
    generateOnlyRawFiles: false,
    height: DEFAULT_HEIGHT_RESOLUTION,
    width: DEFAULT_WIDTH_RESOLUTION,
    rawFilesFolderPath: '',
    outputFolderPath: '',
    hlae: {
      customLocationEnabled: false,
      customExecutableLocation: '',
      configFolderEnabled: false,
      configFolderPath: '',
    },
  },
  playerProfile: {
    gameModes: [],
    games: [],
    demoSources: [],
    demoTypes: [],
    ranking: RankingFilter.All,
    tagIds: [],
    maxRounds: [],
    startDate: undefined,
    endDate: undefined,
  },
  download: {
    folderPath: undefined,
    downloadValveDemosAtStartup: true,
    downloadValveDemosInBackground: true,
    downloadFaceitDemosAtStartup: true,
    downloadFaceitDemosInBackground: true,
  },
  matches: {
    gameModes: [],
    demoTypes: [],
    sources: [],
    games: [],
    ranking: RankingFilter.All,
    tagIds: [],
    maxRounds: [],
    startDate: undefined,
    endDate: undefined,
  },
  players: {
    bans: [],
    startDate: undefined,
    endDate: undefined,
  },
  ban: {
    ignoreBanBeforeFirstSeen: true,
  },
};
