import type { TeamNumber, WeaponName, WeaponType } from 'csdm/common/types/counter-strike';
import type { BaseEvent } from 'csdm/common/types/base-event';

export type Kill = BaseEvent & {
  killerSteamId: string;
  killerName: string;
  killerSide: TeamNumber;
  killerTeamName: string;
  killerX: number;
  killerY: number;
  killerZ: number;
  isKillerAirborne: boolean;
  isKillerBlinded: boolean;
  victimSteamId: string;
  victimName: string;
  victimSide: TeamNumber;
  victimTeamName: string;
  victimX: number;
  victimY: number;
  victimZ: number;
  isVictimAirborne: boolean;
  isVictimBlinded: boolean;
  assisterSteamId: string;
  assisterName: string;
  assisterSide: TeamNumber;
  assisterTeamName: string;
  assisterX: number;
  assisterY: number;
  assisterZ: number;
  isHeadshot: boolean;
  penetratedObjects: number;
  isAssistedFlash: boolean;
  isKillerControllingBot: boolean;
  isVictimControllingBot: boolean;
  isAssisterControllingBot: boolean;
  isTradeKill: boolean;
  isTradeDeath: boolean;
  isThroughSmoke: boolean;
  isNoScope: boolean;
  distance: number;
  weaponName: WeaponName;
  weaponType: WeaponType;
};
