import type { DemoSource, DemoType, Game, TeamNumber, GameMode } from 'csdm/common/types/counter-strike';
import type { Team } from './team';
import type { Round } from './round';
import type { ChatMessage } from './chat-message';
import type { MatchPlayer } from './match-player';
import type { Damage } from './damage';
import type { Shot } from './shot';
import type { Kill } from './kill';
import type { PlayerBlind } from './player-blind';
import type { Clutch } from './clutch';
import type { BombPlanted } from './bomb-planted';
import type { BombDefused } from './bomb-defused';
import type { PlayerPosition } from './player-position';
import type { GrenadePosition } from './grenade-position';
import type { ChickenDeath } from './chicken-death';
import type { ChickenPosition } from './chicken-position';
import type { BombExploded } from './bomb-exploded';
import type { PlayerEconomy } from './player-economy';
import type { TeamEconomyStats } from './team-economy-stats';

export type Match = {
  checksum: string;
  demoFilePath: string;
  game: Game;
  name: string;
  source: DemoSource;
  type: DemoType;
  serverName: string;
  clientName: string;
  tickCount: number;
  tickrate: number;
  frameRate: number;
  duration: number;
  gameMode: GameMode;
  isRanked: boolean;
  mapName: string;
  killCount: number;
  deathCount: number;
  assistCount: number;
  collateralKillCount: number;
  shotCount: number;
  players: MatchPlayer[];
  rounds: Round[];
  kills: Kill[];
  blinds: PlayerBlind[];
  clutches: Clutch[];
  shots: Shot[];
  bombsPlanted: BombPlanted[];
  bombsDefused: BombDefused[];
  bombsExploded: BombExploded[];
  chatMessages: ChatMessage[];
  playersEconomies: PlayerEconomy[];
  playerPositions: PlayerPosition[];
  grenadePositions: GrenadePosition[];
  chickenPositions: ChickenPosition[];
  chickenDeaths: ChickenDeath[];
  teamA: Team;
  teamB: Team;
  winnerName: string;
  winnerSide: TeamNumber;
  maxRounds: number;
  date: string;
  comment: string;
  analyzeDate: string;
  damages: Damage[];
  tagIds: string[];
  shareCode: string;
  hasVacLiveBan: boolean;
  teamsEconomyStats: TeamEconomyStats[];
};
