import type { TeamNumber, WeaponName } from 'csdm/common/types/counter-strike';
import type { BaseEvent } from 'csdm/common/types/base-event';

export type PlayerPosition = BaseEvent & {
  isAlive: boolean;
  frame: number;
  x: number;
  y: number;
  z: number;
  yaw: number;
  flashDurationRemaining: number;
  side: TeamNumber;
  money: number;
  health: number;
  armor: number;
  hasHelmet: boolean;
  hasBomb: boolean;
  hasDefuseKit: boolean;
  isDucking: boolean;
  isAirborne: boolean;
  isScoping: boolean;
  isDefusing: boolean;
  isPlanting: boolean;
  isGrabbingHostage: boolean;
  activeWeaponName: WeaponName;
  equipments: string;
  grenades: string;
  pistols: string;
  smgs: string;
  rifles: string;
  heavy: string;
  playerSteamId: string;
  playerName: string;
};
