import type { CompetitiveRank, PremierRank } from './counter-strike';
import type { EconomyBan } from 'csdm/node/steam-web-api/steam-constants';
import type { PlayerUtilityStats } from 'csdm/node/database/players/fetch-players-utility-stats';
import type { PlayerOpeningDuelsStats } from 'csdm/node/database/player/fetch-player-opening-duels-stats';

export type Player = {
  steamId: string;
  name: string;
  avatar: string | null;
  matchCount: number;
  premierRank: PremierRank;
  competitiveRank: CompetitiveRank;
  comment: string;
  lostMatchCount: number;
  tiedMatchCount: number;
  wonMatchCount: number;
  roundCount: number;
  roundCountAsCt: number;
  roundCountAsT: number;
  killCount: number;
  deathCount: number;
  assistCount: number;
  damageHealth: number;
  damageArmor: number;
  averageDamagePerRound: number;
  averageKillsPerRound: number;
  averageDeathsPerRound: number;
  averageUtilityDamagePerRound: number;
  headshotCount: number;
  headshotPercentage: number;
  mvpCount: number;
  firstKillCount: number;
  firstDeathCount: number;
  bombPlantedCount: number;
  bombDefusedCount: number;
  killDeathRatio: number;
  kast: number;
  utilityDamage: number;
  tradeKillCount: number;
  tradeDeathCount: number;
  firstTradeKillCount: number;
  firstTradeDeathCount: number;
  oneKillCount: number;
  twoKillCount: number;
  threeKillCount: number;
  fourKillCount: number;
  fiveKillCount: number;
  collateralKillCount: number;
  wallbangKillCount: number;
  hostageRescuedCount: number;
  hltvRating: number;
  hltvRating2: number;
  winsCount: number;
  lastBanDate: string | null;
  vacBanCount: number;
  gameBanCount: number;
  isCommunityBanned: boolean;
  economyBan: EconomyBan;
  hasPrivateProfile: boolean;
  openingDuelsStats: PlayerOpeningDuelsStats;
} & PlayerUtilityStats;
