import type { MatchTable } from 'csdm/common/types/match-table';
import type { Clutch } from './clutch';
import type { LastMatch } from './last-match';
import type { MapStats } from './map-stats';
import type { TeamEconomyStats } from './team-economy-stats';
import type { TeamMatchSideStats } from './team-match-side-stats';
import type { TeamBombsStats } from './team-bombs-stats';

export type TeamProfile = {
  name: string;
  assistCount: number;
  averageDamagePerRound: number;
  averageDeathsPerRound: number;
  averageKillsPerRound: number;
  bombDefusedCount: number;
  bombPlantedCount: number;
  deathCount: number;
  fiveKillCount: number;
  fourKillCount: number;
  headshotCount: number;
  headshotPercentage: number;
  hostageRescuedCount: number;
  kast: number;
  hltvRating: number;
  hltvRating2: number;
  killCount: number;
  collateralKillCount: number;
  wallbangKillCount: number;
  killDeathRatio: number;
  lostMatchCount: number;
  matchCount: number;
  oneKillCount: number;
  roundCount: number;
  roundCountAsCt: number;
  roundCountAsT: number;
  threeKillCount: number;
  tiedMatchCount: number;
  twoKillCount: number;
  wonMatchCount: number;
  clutches: Clutch[];
  mapsStats: MapStats[];
  lastMatches: LastMatch[];
  matches: MatchTable[];
  economyStats: TeamEconomyStats;
  sideStats: TeamMatchSideStats;
  bombsStats: TeamBombsStats;
};
