//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGO_Demos_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCheckUpdate {
            get {
                return ((bool)(this["EnableCheckUpdate"]));
            }
            set {
                this["EnableCheckUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFolder {
            get {
                return ((string)(this["LastFolder"]));
            }
            set {
                this["LastFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAllFolders {
            get {
                return ((bool)(this["ShowAllFolders"]));
            }
            set {
                this["ShowAllFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int ResolutionWidth {
            get {
                return ((int)(this["ResolutionWidth"]));
            }
            set {
                this["ResolutionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("768")]
        public int ResolutionHeight {
            get {
                return ((int)(this["ResolutionHeight"]));
            }
            set {
                this["ResolutionHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFullscreen {
            get {
                return ((bool)(this["IsFullscreen"]));
            }
            set {
                this["IsFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long SteamID {
            get {
                return ((long)(this["SteamID"]));
            }
            set {
                this["SteamID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPovDemos {
            get {
                return ((bool)(this["ShowPovDemos"]));
            }
            set {
                this["ShowPovDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEbotDemos {
            get {
                return ((bool)(this["ShowEbotDemos"]));
            }
            set {
                this["ShowEbotDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEseaDemos {
            get {
                return ((bool)(this["ShowEseaDemos"]));
            }
            set {
                this["ShowEseaDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowValveDemos {
            get {
                return ((bool)(this["ShowValveDemos"]));
            }
            set {
                this["ShowValveDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDateColumn {
            get {
                return ((bool)(this["ShowDateColumn"]));
            }
            set {
                this["ShowDateColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBombPlantedColumn {
            get {
                return ((bool)(this["ShowBombPlantedColumn"]));
            }
            set {
                this["ShowBombPlantedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBombDefusedColumn {
            get {
                return ((bool)(this["ShowBombDefusedColumn"]));
            }
            set {
                this["ShowBombDefusedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDemoNameColumn {
            get {
                return ((bool)(this["ShowDemoNameColumn"]));
            }
            set {
                this["ShowDemoNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMapNameColumn {
            get {
                return ((bool)(this["ShowMapNameColumn"]));
            }
            set {
                this["ShowMapNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTeam1NameColumn {
            get {
                return ((bool)(this["ShowTeam1NameColumn"]));
            }
            set {
                this["ShowTeam1NameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTeam2NameColumn {
            get {
                return ((bool)(this["ShowTeam2NameColumn"]));
            }
            set {
                this["ShowTeam2NameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowScoreTeam1Column {
            get {
                return ((bool)(this["ShowScoreTeam1Column"]));
            }
            set {
                this["ShowScoreTeam1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowScoreTeam2Column {
            get {
                return ((bool)(this["ShowScoreTeam2Column"]));
            }
            set {
                this["ShowScoreTeam2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHostnameColumn {
            get {
                return ((bool)(this["ShowHostnameColumn"]));
            }
            set {
                this["ShowHostnameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClientnameColumn {
            get {
                return ((bool)(this["ShowClientnameColumn"]));
            }
            set {
                this["ShowClientnameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDemoTypeColumn {
            get {
                return ((bool)(this["ShowDemoTypeColumn"]));
            }
            set {
                this["ShowDemoTypeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTickrateColumn {
            get {
                return ((bool)(this["ShowTickrateColumn"]));
            }
            set {
                this["ShowTickrateColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOneKillColumn {
            get {
                return ((bool)(this["ShowOneKillColumn"]));
            }
            set {
                this["ShowOneKillColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTwoKillsColumn {
            get {
                return ((bool)(this["ShowTwoKillsColumn"]));
            }
            set {
                this["ShowTwoKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowThreeKillsColumn {
            get {
                return ((bool)(this["ShowThreeKillsColumn"]));
            }
            set {
                this["ShowThreeKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFourKillsColumn {
            get {
                return ((bool)(this["ShowFourKillsColumn"]));
            }
            set {
                this["ShowFourKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFiveKillsColumn {
            get {
                return ((bool)(this["ShowFiveKillsColumn"]));
            }
            set {
                this["ShowFiveKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTotalKillsColumn {
            get {
                return ((bool)(this["ShowTotalKillsColumn"]));
            }
            set {
                this["ShowTotalKillsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBombExplodedColumn {
            get {
                return ((bool)(this["ShowBombExplodedColumn"]));
            }
            set {
                this["ShowBombExplodedColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDeathsColumn {
            get {
                return ((bool)(this["ShowDeathsColumn"]));
            }
            set {
                this["ShowDeathsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAssistsColumn {
            get {
                return ((bool)(this["ShowAssistsColumn"]));
            }
            set {
                this["ShowAssistsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowKdColumn {
            get {
                return ((bool)(this["ShowKdColumn"]));
            }
            set {
                this["ShowKdColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHsColumn {
            get {
                return ((bool)(this["ShowHsColumn"]));
            }
            set {
                this["ShowHsColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTkColumn {
            get {
                return ((bool)(this["ShowTkColumn"]));
            }
            set {
                this["ShowTkColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEkColumn {
            get {
                return ((bool)(this["ShowEkColumn"]));
            }
            set {
                this["ShowEkColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMvpColumn {
            get {
                return ((bool)(this["ShowMvpColumn"]));
            }
            set {
                this["ShowMvpColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPlayerScoreColumn {
            get {
                return ((bool)(this["ShowPlayerScoreColumn"]));
            }
            set {
                this["ShowPlayerScoreColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v1Column {
            get {
                return ((bool)(this["ShowClutch1v1Column"]));
            }
            set {
                this["ShowClutch1v1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v2Column {
            get {
                return ((bool)(this["ShowClutch1v2Column"]));
            }
            set {
                this["ShowClutch1v2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v3Column {
            get {
                return ((bool)(this["ShowClutch1v3Column"]));
            }
            set {
                this["ShowClutch1v3Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v4Column {
            get {
                return ((bool)(this["ShowClutch1v4Column"]));
            }
            set {
                this["ShowClutch1v4Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutch1v5Column {
            get {
                return ((bool)(this["ShowClutch1v5Column"]));
            }
            set {
                this["ShowClutch1v5Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStartMoneyTeam1Column {
            get {
                return ((bool)(this["ShowStartMoneyTeam1Column"]));
            }
            set {
                this["ShowStartMoneyTeam1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStartMoneyTeam2Column {
            get {
                return ((bool)(this["ShowStartMoneyTeam2Column"]));
            }
            set {
                this["ShowStartMoneyTeam2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEquipementValueTeam1Column {
            get {
                return ((bool)(this["ShowEquipementValueTeam1Column"]));
            }
            set {
                this["ShowEquipementValueTeam1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEquipementValueTeam2Column {
            get {
                return ((bool)(this["ShowEquipementValueTeam2Column"]));
            }
            set {
                this["ShowEquipementValueTeam2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTickColumn {
            get {
                return ((bool)(this["ShowTickColumn"]));
            }
            set {
                this["ShowTickColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWinnerClanNameColumn {
            get {
                return ((bool)(this["ShowWinnerClanNameColumn"]));
            }
            set {
                this["ShowWinnerClanNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWinColumn {
            get {
                return ((bool)(this["ShowWinColumn"]));
            }
            set {
                this["ShowWinColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWinnerSideColumn {
            get {
                return ((bool)(this["ShowWinnerSideColumn"]));
            }
            set {
                this["ShowWinnerSideColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DateFormatEuropean {
            get {
                return ((bool)(this["DateFormatEuropean"]));
            }
            set {
                this["DateFormatEuropean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOldDemos {
            get {
                return ((bool)(this["ShowOldDemos"]));
            }
            set {
                this["ShowOldDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFaceitDemos {
            get {
                return ((bool)(this["ShowFaceitDemos"]));
            }
            set {
                this["ShowFaceitDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDurationColumn {
            get {
                return ((bool)(this["ShowDurationColumn"]));
            }
            set {
                this["ShowDurationColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
            set {
                this["ApplicationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFramerateColumn {
            get {
                return ((bool)(this["ShowFramerateColumn"]));
            }
            set {
                this["ShowFramerateColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCevoDemos {
            get {
                return ((bool)(this["ShowCevoDemos"]));
            }
            set {
                this["ShowCevoDemos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOnlyUserStats {
            get {
                return ((bool)(this["ShowOnlyUserStats"]));
            }
            set {
                this["ShowOnlyUserStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCommentColumn {
            get {
                return ((bool)(this["ShowCommentColumn"]));
            }
            set {
                this["ShowCommentColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClutchCountColumn {
            get {
                return ((bool)(this["ShowClutchCountColumn"]));
            }
            set {
                this["ShowClutchCountColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LaunchParameters {
            get {
                return ((string)(this["LaunchParameters"]));
            }
            set {
                this["LaunchParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTotalDamageHealthColumn {
            get {
                return ((bool)(this["ShowTotalDamageHealthColumn"]));
            }
            set {
                this["ShowTotalDamageHealthColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTotalDamageArmorColumn {
            get {
                return ((bool)(this["ShowTotalDamageArmorColumn"]));
            }
            set {
                this["ShowTotalDamageArmorColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAverageDamageColumn {
            get {
                return ((bool)(this["ShowAverageDamageColumn"]));
            }
            set {
                this["ShowAverageDamageColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBanColumns {
            get {
                return ((bool)(this["ShowBanColumns"]));
            }
            set {
                this["ShowBanColumns"] = value;
            }
        }
    }
}
