name: Close stale issues

on:
  schedule:
    - cron: '0 0 * * *' # Once a day

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Close stale issues
        uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: ''
          close-issue-message: 'This issue was closed due to inactivity. Feel free to reopen if needed.'
          days-before-pr-stale: -1
          days-before-issue-stale: 23
          days-before-issue-close: 7
          stale-issue-label: 'stale'
          any-of-labels: 'reply-needed'
          exempt-issue-labels: 'V2'
