name: Validate

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: TS compile
        run: vp run compile

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: Lint
        run: vp run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: Code format
        run: vp run format -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - name: Test
        run: vp run test

      - name: Check if the English source strings have been extracted
        id: git-diff
        run: |
          vp run i18n:extract
          git diff --ignore-blank-lines src/ui/translations/en src/electron-main/translations/en
          echo "MODIFIED=$(if [ -n "$(git diff --ignore-blank-lines src/ui/translations/en src/electron-main/translations/en)" ]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - name: Fail if the English source strings have not been extracted
        if: steps.git-diff.outputs.MODIFIED == 'true'
        run: |
          echo "::error title=Translations not up-to-date::The English source strings are not extracted. Please run 'vp run i18n:extract' and commit the changes."
          exit 1

      - name: Find dead code
        run: vp run deadcode
